// js/pdfService.js - VERSÃO DEFINITIVA COM LOGO DA DEFENSORIA (SOMENTE NA ATA)

const ensureJsPDF = async () => {
    if (typeof window.jspdf === 'undefined') {
        console.log("Baixando biblioteca PDF...");
        await new Promise((resolve) => {
            const script = document.createElement('script');
            script.src = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";
            script.onload = resolve;
            document.head.appendChild(script);
        });
        await new Promise((resolve) => {
            const script2 = document.createElement('script');
            script2.src = "https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.31/jspdf.plugin.autotable.min.js";
            script2.onload = resolve;
            document.head.appendChild(script2);
        });
    }
};

const cleanString = (str) => String(str || '').replace(/"/g, '');

const getSafeDate = (timeValue) => {
    if (!timeValue) return null;
    if (typeof timeValue === 'object' && timeValue.seconds) {
        return new Date(timeValue.seconds * 1000);
    }
    const date = new Date(timeValue);
    return isNaN(date.getTime()) ? null : date;
};

const calculateDuration = (totalMinutes) => {
    if (totalMinutes === null || totalMinutes < 0) return 'N/A';
    return totalMinutes >= 60 
        ? `${Math.floor(totalMinutes / 60)}h ${totalMinutes % 60}min` 
        : `${totalMinutes} min`;
};

const formatCurrency = (value) => {
    if (!value) return 'R$ 0,00';
    if (typeof value === 'string' && value.includes('R$')) return value;
    
    let num = 0;
    if (typeof value === 'string') {
        const cleanValue = value.replace(/[R$\s]/g, '').replace(',', '.');
        num = parseFloat(cleanValue) || 0;
    } else {
        num = value || 0;
    }
    
    return num.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
};

const getIdentificador = (colaborador) => {
    if (colaborador.identificador) return colaborador.identificador;
    if (colaborador.id) return colaborador.id;
    if (colaborador.matricula) return colaborador.matricula;
    if (colaborador.codigo) return colaborador.codigo;
    return '';
};

const getAttendantNameForPDF = (item) => {
    if (!item) return 'N/A';
    if (item.attendedBy) {
        const name = typeof item.attendedBy === 'object' ? (item.attendedBy.nome || item.attendedBy.name) : item.attendedBy;
        if (name) return String(name).trim();
    }
    if (item.assignedCollaborator && item.assignedCollaborator.name) {
        return String(item.assignedCollaborator.name).trim();
    }
    if (item.attendant) {
        const name = typeof item.attendant === 'object' ? (item.attendant.nome || item.attendant.name) : item.attendant;
        if (name) return String(name).trim();
    }
    return 'N/A';
};

// ⭐ LOGO DA DEFENSORIA (Resgatada do seu código original para burlar o bloqueio do Firebase)
const LOGO_PADRAO_BASE64 = "iVBORw0KGgoAAAANSUhEUgAAAhcAAAB4CAYAAABB5NDuAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAGX7SURBVHhe7Z11eBRX24fv9biQBEICwSG4uxTX4lqkUKTUjbaUektLjSq0SIG2tEhxK1YcikNwCRBIIEAICXFZm++PCDuzs8luSCjv17mv67TkOWdnZ3dHfnPOIypBEAQUFBQUFBQUFIoJtdSgoKCgoKCgoPAgKOJCQUFBQUFBoVhRxIWCgoKCgoJCsaKICwUFBQUFBYViRREXCgoKCgoKCsWKIi4UFBQUFBQUihVFXCgoKCgoKCgUK4q4UFBQUFBQUChWFHGhoKCgoKCgUKwo4kJBQUFBQUGhWFHEhYKCgoKCgkKxoogLBQUFBQUFhWJFERcKCgoKCgoKxYoiLhQUFBQUFBSKFUVcKCgoKCgoKBQrirhQUFBQUFBQKFYUcaGgoKCgoKBQrCjiQkFBQUFBQaFYUcSFgoKCgoKCQrGiiAsFBQUFBQWFYkURFwoKCgoKCgrFiiIuFBQUFBQUFIoVRVwoKCgoKCgoFCuKuFBQUFBQUFAoVlSCIAhS46OEIAgYs9NJTY0nLeUOqal3yEi/h9GYgcmYicViwmIxo1Zr0Onc0Onc0Orc0Os98PIOxNunNN4+ZfD0LIVKrWgpBQUFBQWFkuaRExeCIJCSfJv4uMvcibvE3TuXyc5Olw5zGbVag59/OUoHV6dMcHUCgiqh0eikwxQUFBQUFBQekEdCXAiCQEL8VaKvHiH2xmmys1KlQ4odtVpLUOkqhFVqQrny9dHqDNIhCgoKCgoKCkXgXxUX6WmJXLtykOhrR0lPS5B2PzQ0Gj3lwupTsXIzgspUQ6VSSYcoKCgoKCgoOMm/Ii5SkuO4eG4b0VePIghWaXehWK3WnGYREBDI+wQqFahUKjQaNWq1ukgiwb9UeWrW6UpIuTqoVIqPhoKCgoKCgqs8VHGRnHSLc6c2ceP6SWmXLFargNlsxmQyYzabcXPzx8PLDw8PPzy9/HHz8EGl0eWIAMGK1WrBmJlGRvo90tOSyEhPIj39Lmq1Cp1Oi06nQavVSt9GFh/fYGrW6Ur5Co2KJFIUFBQUFBT+qzwUcWEyZXHu1CYuXdxNYW9nsVjIzjZhtaopU7YGQcFV8C1dkZAylUjLzuBG0h1iU+O5nhJPbGoCWWYjZqsFjUqNXqOjtJcfFbyDCPUJIsQ3iGCfQG7fvU5i3FUS465yI+YsZnM6BoMevV6HWl2wcAgMqkyjpoPx9Q8R2bdEHmLfhc94vs07BJdqKupTUFBQUFD4L1Oi4kIQBG7EnODEsVVkZaZIu/MRBIGsLCOgp3yF+oRUaUS5kBocjj7NzuhTHIk9z9EbF7ibkSx9aaF46txoGFKdJuXCaVu+Dp2rNSUxKY6bUce5evkYmRl3cXd3Q693HDmiUqmoFt6earU6s/zsHr7Zt5SqnlH4VvSgb0Bt+jb8VvoSBQUFBQWF/ywlJi5MxkyOHlxS4BKIxWIhMyMbv1IVqFavIxUq1GXzxYMsP7ebzRcPkWrMkL7kgdGqNbSrWJ8BtR9jcJ32pCbf4dLJ7cRcjcDNXYebm8HhMkiCycTXMZcpVyqDauEemFARqlbxScfN0qEKCgoKCgr/WUpEXCQmxHBw368OI0CsVisZ6VmULVeP2k0fx6zW8u2BFfx2fCMp2cUvKByhVWvoV6str7UcTI3A8pyJ2MKF0ztwd9fi5iYfmmrWJbGv1E0ybJKbftLgPUID24jGKSgoKCgo/FcpdnFxOXIvJ46uko0CEQSBzMwsfP0q0qj1EJKsFib/PYctkYco1p0oAnXLVGZqp3G0CavN8QOriLp0EC8vd9FyiaDJ4HDgNRIkWdP7lKpB/0Y/iGwKCgoKCgr/VYpNXAiCwOkT67l4bru0CwCz2YLJrKFZu1F4lArhza2zWXZq+78uKqQ0L1+Lb3u8QJinH/u2/kx62m28vDxQaUycDLpMrEw5ljIq+LzTFqlZQUFB4T/JwZgzBHn6USWgnLRL4T9CsYgLq9XC0YNLib56WNoFQHp6JqWDa9Gy42hmHlrN1B2/YrJapMMeKYbV68SPvV/jXMQWTkds4E6VWK4Z5J0+a6qMTCrbBHXoMFS+jaXdCgoKCv8ZEjNSqPnNE8SnJ/F4eGteaTOUDpWVkP7/Gg8sLiwWMwf2zOfWzXPSLqxWgcxMMw1bDsYvpDpD//yQQ9ftxz0oWrUGcwmIlVCfQBYNfo9QTwPfHPiYZE0Cek+xwAhTmZisS8Zdlfs1elSBskOgTC9UGg/RWAUFBYX/74xbMY0Fx/4S2eoFV+Hvcd9T2stfZFf4/4v9HL8LCFYrh/5ZKCssLBYLWl0AvQa/z7HMVGp//6TLwkKjhvz0mwXwTa8X8UJ+VuFBiE25S4f5L/Pj0R182u1nmpdqT1ZSVn6ujiAsvGorLAAyrsCVz+BQN4T0K/ftCgoKCv/P2XHlmJ2w0KjUTH5spCIs/mMUWVwIgsDxoyuIlQk1NZlM6A2l6dz7FSZu+J5xq78g3ZQlHVYgOg0MaOlBsJsVss3SbhFP1O9Ci5CaYCr+2QsB+G7/MtrOfYEBdSbQIbQ3mYlZeFstTNIn4WsrLGwJHYXKs4rUqqCgoPD/kkxTNk+v+kJkM2h0rB71GcMbdBXZFf7/U2Rxce70ZqIu/SM1YzKZMLgF0+nxlxny54esPrdHOiQfjRqqltXirbWC5X50SViQhg51DHi6qQkL1hUoGoI8/Qj09KNWmUpgvb8NtQq0GsDq4ObvImfvXKXt3BfoGT6CrmG9GZEST6Agv1+mgN6oKjwtNSsoKCj8v+Xj7Qu4khib/7eX3p3NY7+hd00lTP+/SJHERez1k5w7bZ84Kk9YdO6dIyy2XpJ38MzDYoX4FAv92nrTooqOxmEanmjrQYe6boQE5ixzmM0CFOAHVKt0xZz/B1cGy30hEV5OR82yGsgy2Yx+MK4l3abt3BfoHj6SsLCB3E4wYpWIl6h73mw6Zyg0zbmCgoLC/xeuJ8Xx14X91AyqQM2gCtQPrsqO8TNoX7mRdKjCfwSXxUV6WgJHDiyWmjGbzS4JizyS0wXMFgiv4k7dau4Y9OJqpllZ1pxypw4ID6qQ8//givmzHxo11K2oI6SUpsBZj6JwLek2bea+gFBtAupyQ7mdYMwXErdS3dkWVZ70tFguR+6VvlRBQUHh/yXl/cpw6pXfOffaYs69tpgTL/9G0/I1pcMU/kO4FC1itZjZsfV77iXGiO1WKzpDaTr1esklYZFHvxYe+HqoZEOVdh9K5updK7jJO2y+2W4EX/R4jhPXL9Lw8yfAx506YTqaVDNgsQosWRuP2dMt1zu0+KjoF8w/T89EdelnNLeXoXXzYtWFSrh7++cWRNPQseur+AeUl760WEnOSmP12d1Ssyw6tZZg7wDqBlcpsnPVvcwU1p4rHuEU5hdMxyri0N276UlsuGC/3FYUvA0eDKzTQWTbEnmIW6l3RbaiMqhOB7wM4oigjRf2cyf9nsjWJLQmdYIri2wF8UfEZrvop4Yh1alftprIJkdKVjqbLh5gZ9Rx4tISyTBlo1VrKOcbRK3SlWgYUp1WYXXQapyrDuwIq9XKwetnOXT9LBE3I7mSEEuW2YhOoyXEO5CGIdVpHFqDjlUa46aTz3brCFePAY1Kg4feQBmvUrQoX9ulz6aa0lpqAkD4zPn3t+WznQvtaiD1Cm9ld5wXN9fu3WJX1HGpWRaDRo+XwZ3qgeWpHhgme92VsubsHpKyUkU2ufPXEcdjL3Lq9mWpmTGNe0lNXLp7nX+iT0nNDlGr1Hjo3KgeWJ66wVWc+jwAh6+f49ydqyKbVq1hZMPuIltRKK7jymq18k/0KQ5dP0fEzUiu3rtFttmIXqPDz92L8KAKNC1Xk85Vmxb5mm7Lxgv72X7lmMhW3rc0r7QZKrI5g0vi4lTEOrskWYIgYLW40WPQO7LCQqMGgxbc9Co8dSquxxlBLz75fTxUNK6ip0JpewFx7HQap68ZwUMv7aJxVT2vtRzN8FpjiL53lTGLnkDwcqNsaR1u+hwxcepCOldumUg2qkFbMgLDdPJLNh25ildAWQyG+/vp6RVA116T0Wpdu7i6QmR8DDW+eUJqLpRgr1L0rtmGsU160bx8badPyDO3o6j7/SipuUj0r9WOVaM+E9mO3jhP0x/Hi2xFpXKpEK68sVxk6/Tzi+xw8iJcGNGTVxLmFyyytZ41kf0xZ0S2EO9AIl761emT3+v9TnYO0FO7TODdjmNENlvSjZm8tXkWC45uIMOULe0WEeTpx+hGPXij3Qin9ymPLFM2cw6v5Yf9y4lKvCnttsPf3ZvxTXrzervhTr/XgxwDpdy96V2zDf1rt6N3eBvU6oLP+eK6CQCcuBlJwxlPSc00CQ3n8PPznD7HisKK0zsZvPhdqblQKvoFM6pRdyY260eob5C0O5+6343kTJz4Rty3ZlvWPPm5yOaI97bO5ZOdv0nNst/zgqMbGLdSfF1wllCfQHpUb8kLrQYWKsZf2/AD3/7zp8jmoTOQ/vEOka0oPOhxlW02MvvQGr7b9yfXkm5Lu+3QqjX0qdmGKe1H0aRc0WaMrFYr4d88waWEGyK7Crj8xjIqlwoV2Quj4DPPhqR7sUSet//S09IyadF5HB/s+MVOWDze1J1RHbwY0taLPs09qVpGA1niyI9SXmq6NXSXFRYAjet6USVYi7tgxssA4SEaOtTW07WenmrBWjwMGgB0ag2BfloqlTPkCwuAeuGedG7mDWlZToW1usK1pNv0X/wevk3eR+VWxu7ikZ6WwPnTW0W2R4XbaYn8fGQdLWdNpMv8l4mMF89GKRQfN1PvMuLPD7GUQC4WgNjkeJr/OIGZB1YWKiwA4tOTmL53CVW/GsJnOxdishQcjZXHoZizNJrxFK9s+N4pYQFwLzOVr/Yupta3w1kUsaXEfZESM1P57fgm+v0+hV6/vU5CuuuVlIvKjP0rpCYAjsZe4ND1s1LzI8G1pNtM3fErNb4exvLT9tf3/zViU+4y7+h6ms4cx6yDq6Td/xOcuBlJ05njeGXD904JCwCz1cKqs7tp9uN4XtvwA9lmo3RIoWy9dNhOWJAbMfnjAde/S6fEhSBYOX54md2FwZhtokadLlzLSOGH/eInRICo2+KLVoVQA60beNKyqpY21XX0auRGn+YeeLoVvBttm/owtLMfg9p40aKmOxWC9YQE6XEzqAt09swjLd2SEz5SAk8Oh2+c5/sDq+jQ61lSUtLtHDwvnt9BSnKcyPaosf3KMep9/yQ//GP/GyoUD9suH2Xqjl+l5gcm05RNp3kvcVYyvesMqcYM3t46h0l/zZB22fHTgVW0mj2R8/HR0i6nSMhIYeSyj3lqxadOi5kHZXPkIdr//DzpxkxpV7GTkJ7M4pN/S835OBIejwrppiyGLH6P+UfWS7v+JzFZLTy39muWntwm7XqkWXLib5r+OJ7TcVHSLqcQgG//+ZMOP7/IvcwUaXeBzDjg+BhdcHSDy+dRwXf1XK5FHSbh7jWRzWoVMHgEUbNBF0Ys/8SuRkiDSnoaVLJfyqhWyZ0aFdyoWt5AkL/za6OOUOd+BOmsgS13EkzF7nNhyye7fiNNq6dGnQ6kpYmrugqClYgjy+2E2aNGtsXEyxu+492tcx/5ff1f5ePtC9gaeUhqfiBmHljBxbtFn3Xy1LnxcuvBUrOInw6s4vl1X2MthuPit+ObGLXsY6w2YeMlyZm4q7yx8UepudiZd3Q9WQU8LS4/vYPbqfJVoh8lnl79BUdvnJea/2eZuuOXh3asPSirz+5m5LKP7PytisLlhBvcyxT7yBTE5bs32HTxgNScT1JWGn9EuFY/q1CfC7PZyMY1H5GdnSayp2cY6THgXV7cMovlp3eK+gCCfNR0b+yORu34pl8U9GoDge7BeOm80asNtA3tRrMyj3Ev4y6zD32BygcyzekkZN0h3ZTz5aZnWoiJNXLjrpl0MySlC8Xuf1E1IJSjz/7MhuWfgjUNvaQOSat2YwktX19kKw4c+Vy0r9SQ6kH3nUkFAdKMGUQl3iw0U+ovg96WdbSiAJ+LofU6Ucm/rNRcILXLVLJznnK03t61WjMq+ov9Gwoj0MOPT7tNFNnkfC4qlwphSN2OIpszTH5sJH7u3iKbnM+FLYEevkS89CvlfEtLu/Jx1ufCarVS5avBdlOneo2WKe2fpEf1Fvi7e5OSnc7xm5EsPrGV3VdPiMbO6f8mTzfrK7LZcvj6OVrOetqhsCjvW5oRDbrSMKQ6Xnp30oyZnImL4o+ILVy9d0s6PJ9ve73k0EnMlWNAECDLnM2RG+e54GBpz6DRceuddfi7+0i7HnhtHMBsMVPlqyHEFDJD+WGnsXzQeZzUXCw48rkYWLs9AZ73P7fVKpCQkczOqOMkZYmv6Xk8Ht6K9aO/Etn+bZ8LFfBlj+dFNgCrYOVO2j22XT7KSRmHUYBNY76me40WUvMj5XMRk3Sb2t+OJM3B7ECQpx8jG3SjeflaeBs8SDNmciz2IuvP77ObTXTT6tk5YQYtwuqI7AXx6obv+e6fZVKziNqlK3H6ld8LfJC3pVBxcenCLk4cWy2ymUxmKod35rqbF0P+/FDUZ0vvpu4E+OT4RLiKTq2nml9tqvnWprR7CKXdyxLkURZfg71TWFJmIn7upaRmMk0ZxGfcIj4jjlvpMVxOOseCHQe4Y0zH20uLxWzl6i1TTjpQJ7+wgni2eX8mNezO32unExDgK+rz8w+lc483nP5hnMWRuPh9yHt2N+48YpPjmXFgOd/tW0a2xT4PiLfeg1OvLKSijFhwJC7+Hvcdnas2lZpdxtGNZe2oz+lTq63U7DJy4qJXjZZsGDNdZCsqhYkLgNYV6rJzwkx0DqIanBUXVxJuUHW6/Q36654v8Fpb+2MC4OStS3zw93zWnt9Lzxot2TD6K4fHZJYpm4YzxsjetN20er7t9RLjmvaW/Rxmi5nfI7bw8vrvSDWKZ/PIff2Jl36lRm4ouS1FPQaOXD/PoEXvyN7kHYkoV28Ccqw+u5sBf7wtNdsR7FWK6Mmr0Gvl/cseBEfi4sRLv8o6NposZmYfWs0rG763E45qlYrYKWsJ9g7It/3b4kKjUmOe5jhKTRAEJm/6ia/22qdJ+O7xl3m59RCp+ZERF4Ig0PPXSWx2MKv5QaexvNluBB56N2kXgiCw7NR23tz0EzHJcaiA5SM+sYuSK4i07AxCP+tLSrb9eSplx/gf6OBkhFCBj+8Wi4kLMiXUrVYdtep1YtLmn6RdImxyWjlFdb869K88mimNv+an9qt4o9Hn9KsyilYhnajqX0tWWAAciN6JyWI/Jemu8yDMtwqNy7bi8arDeKXJx5x682+OvriUuf0m8+JjHWhR3Y0gg7VY8mHMPbwWq5sXoeVrk5kpdqxLuhfL7ZuPxnRjqG8Qn3d/jm3jv8dHEkpJ7lr8W5tnSc0KxcQ/0ad5e8tsqdllHE17NitfS2rKp37Zaqx58nNWjZzGvAFvORQWAHMOr5UVFnqNlo1jpvNMi/6ywgJAq9HyVJNe7Hp6Jn5uXtJussxG3v97ntT8QDQtX5Of+r0uNUOuM2pJIedPMbReJzQq8eX1dloiK8/sEtn+LXQaLS+2GswLLQdKu7AKgp1z/qOOSqXivU7y0VRGmQeoR4kdV445FBY/D5jMh53HyQoLcj/30PqdOfHyr3Sq0pjpPV9wSVgA/B6x2U5YhPmWoXWFuiIbDo51RxQoLq5dOUSWxCnEmG2iduPH+fnoBq4n3xH1SUnLLHyty98QSO9Kw/my1a9MafI1fSoPp7p/HbRqeXWfYUznXsZdbqfe4Nq9y9zLuEuP8JwTJCohkpvJMSRmxJNuTHPonV/ON4wOFXvxatOpbB2znsVPvs0zrRviI5jAXPg+O8IiWJm0+ScatR5Cenqmne/C+bOPVuRIm4r1WTHiU1mf2OWnd3CjkN9XoehM37uEtQWkxncGjVp+VnBjAWunefSv/RhlfQKl5nysVquskzbAj30nOf300ii0BstHfCI1A7DizE5upsRLzQ9Ej+ot8NbbC+aU7HSpqVg4czuKnTKhzR93Hk8fmbTXBTnN/Rs85WD58256ktT0yOOmNchey8r5OF6CfBT48cBKqQmAF1oOZHzTPlKzLP7uPmwZ+y2vthkm7SoQQRCYKfP+E5v35fkW9sJz7fm9RN9zLoLFobgQBIHI8/a+FGqtFxWrNuHTXQulXXakZzmeugj3r8+rDaYyvc3vDKgymiCP+1PwgiBwJ+0Wx2/sZ+3Zxfx08DPe3TaRcet68vTm3ry0cxhv7h3DBwef5Z/bOd7A9zITmLxpLFMOjuPVPcN5dns/xm3uweRdT/HD4Q9Zce4XDsbsJDY5Gov1vre6t8GHzlX6MKv/LE5PXsa42h0I89OitVqKVJdk/YV/iElPokq1FnazFwnxV0mId92rvyTpUq0Z/Ws/JjVjFYRH5inrfx2dAxEwetknRNnUYnCVAA97HwKAz3b9zrAl7/PPtVNFdmY7FntRNtw0PCiMsY0fl5oLpHPVpjwe3kpqxioIxZaQLQ+1Wo2bzt6RvKAZmgdhpoxY6FSlMdWDwni2RX9pFwdiznAs9oLU/K8R5Ck/G+xMSPOjxuxDq+0CC/QaLV2rNZNYHx0yTdmyCePctHo+6DRWai4QjVrj8nG+48oxzt0RB2vo1BrGNenNgDqPEeTpJ+qzCgKzDjkXlupQXCTcvUZamjiToclkplrtDsw+vNbhlKwtZUvZX1TDvKswqeE0Jjf+knqBzVCr1JgsJiJiDzL34Fe8tXU8T63vwWs7R/Dd6fdZffNXjqTtIpZrWD0s6Dx0aA0aNHoNap0aVa7DqCpXs6o1atRaNRqdBpVexR3zTSJSDvDXzaXMifycd488zYS/ezNl93hmHpnKrqsbSc3OiYUP86/IvDHTOPzcEr4f2I/ONXXULasizBeCvXBacEzdtZDwhl3JzLSvBHst6tGbbnyuxQCpCcCli+BfF/Yz9/Bap1uWixcvAQFBcK05S3TSbbv9K6i56k3fK7wVj1VqIDWTnJ3O4EXvuvxd5BHmF0z94KpSMwB/ntpOmznPUnZab55c9jG/H99MXGqidJhDDt+Qd/od37RPoYmp5JjYrJ/UBLkipjiJjI8hXuapW3qRLA7uZabwe4R9jaU8UdGpShOqBtgnHnJlarmkcRRp5GPwlJr+VayClZ1Xjtm1vy8dZvbB1Qz64x1eWv+d9GW82W4EAZ5i/7dHidO3r2CSmWHvW6stgSVwzEqROxYH1GlPGe9SGLR6xjaxn9n6+fA6Mp24Zjm8SkTL3ARNJoEaNdvw00Gxg6ccXm4qAiXOnL0rDefDZj9SJ6AxZquZLFMmi4/PYcKax/n6+NvsT/mbOPV1VB4COnddjkAoRInliQpXEDRWbpuucyx5H79d+Z5X9g3j80NvcOFuTsrZMt4hPNfsLeb0nkuDMHc6NvGie3MvhnfyoW0NHe4mo6iKq5TNkQex6gwEBlXCmC1e77seE4HlIcX5O0u7Sg3wkEnRfDw2UmpyyHf/LGPi6i+dbq4+GfX7fQrqt9s43ZxNhUxuuKJ0/wpq687vk26iQLRqDUuGfUQZmQyVx29G8upfP0jNTjP5sZFSk4g76Un8HrGFJ5dPJXhab1r8NIE5h9aQVojz1nEHN/0e1e297p2hc9UmsjM4ETedP8YKw2Qx8+YmeT+wbtWaS00PzK/HNtodx2W9A+hTM8fpVK1W80xz+9mLpSe3EZ8mThH/b2C1Wvl67xKpGYCGIfZOoP8mAtBx3kt2reuCV3l27XRWnrWfZR1StyPvu/j0/7A5ceuS1AS5kVElzbV7t1h/wf5a9qzNMTuxWT+7O2xiZipLCsjpkoesuLBYTFyPjhDZrFYrYZWasjPqGDcKWCcN9tfQopqeltXsfSZq+NXFbDWx9uxiXvtrFJujVqLVazBpjOjcdfmzEK6QJz4KEyEFYRWsXEw9xYE724m4fYDZhz7nTvotwvyrYDB5YMl19lSrVVQJc2NAJz+qlsJhxVUB+OHgKmrU70KGZPbCZMzk9s2Scy4rCjqNlkAPe5V8N8P+CVChaJT1CWTpEx+jljlOZx9aw+ITRfPHGVa/M083c25dFuDQ9XM8s+YrKnwxgOl7FjtcNpHWR8mjjJd9VJYzuOkMlJJZxkmQ1OEoiIt3YzgUc1bUDsacYXdUBF/tWUSTmWNZe95+mcVNqy+WSCZbrFarbNbCCU37iJxcxzTqiUEjvhZmW0z8fGSdyPawuXbvFmNWfCLrn+Ot96BxaLjU/D9Fv1pt+WPoBw4djh8V7jgQmUU9z1xh1sHVdpFCtUpXpJ3NLGulUiF0l3mgmLF/RaGzw7Li4vbNc5hM4njb7GwjlWq14QcHKVW93VV0ru9Gh7oGwsP0hJa2X/f88fQnvLZzBMuvzKNy+WpsjP6TakG1sRjlL3DOkDdzUZQZDFt89P7EZ94i25LFgdidvH1gPG/uGUOGPhWNTvzEpdOpad3Ym+rBGsi0j1IhN5yqcuUGCILG7gIeffWo6O9HAb3W/iSUHngKD0b7yo2Y2mWC1AzA06u+4Lxk7dMZVCoVs/u9yU99J+Gpk/colyMxM5U3Nv1I/z+myC7LWByIDnURHgDy0Etusrh4jL256SdazHpa1FrOmkj7n1/gzU0/cer2FelLAHinw2iH3vZFZVPkQa5I/GU0KjUTJEIvwNOXofU6iWzkXtjND2EGc9zKz2g/9/n81m7Oc9T5diSVvhzE7w6SIj3TvF+xf18PmzXn9tJ05jiHM3CPCo6CDqSRRsVNpimbeTIC95nm/ewe1OV8h07culRocTnZTxB3y/4H0Wq88PMtza4o8YwGQFiQhoGtPCkXqMWgk90kkJPcKo0UdB463LUeZGRnkGpOxs+9FIITvgzy5H4RKtUD1Q6p4VeH83EnOXvvOA3KNSc7O4t75nj0nvYXRHIv6q0a+9Cmjjth3gLl/SDIg/yQ1uTsdPZfO0WFSvXJliyNxN26iNXBQfVvkZRpn1DH1+3RWnf9/8Bbj42iZ42WUjPppiwGLXrH5RS75B6Lz7YYwI0pa/j+8Vdo4sJT57rz+3hx3bdSM54Obi7O+FrJIQiC7DFW0mv7/Wq1ZUp7+7wsD8oMmUia3jVbyyZHk7s430iJZ00xO7PKcSz2Iruvnshve6+dLDBVfK3SFR2GdEoR7NwnHeP8yOLj5O3LNPtxPMtO2adTeFSQVlXOo6jnmbMsPrGVRMl7eOgMPNmoh8gG0LNGS8J8y0jNsv4atsgqgbjb4nVQq1UgJKwuGy8ewCLYP9E0rGw/S1EQapU6N2JD4MTdQzQJa4M5u2gq/v7MxYOhUeswWUycTDhE45BWmLOcu/lXrehOx2bedGrsRZs6bpB+/ylw2dndhFRqiNEont0wm7NJumdfIObfIjI+xq5MNEA9B86Ccoxs0I33Oz7ldHPTunbM6NQa3LR6p5vaBeVfNSDUbv8Kau0rN5JuwmnUajULB78ne7Keu3ONZ1Z/5dJF2xY/d29eaj2YIy/MJ3ryShYMfJvh9bvI+nrYsuDYBq5JsmnWDa4i+juP3VHiDJ/OcvLWJdlkWvXLOn+MuYJGpebjzuNZMeJThyG7ReVifDRbZPJAHIw5S73vRtm1CavkE03JCZR/kwp+ZVg76gu8ZQSfRmX/HbqSP0KunozWhd9FBawY8YlsWzZ8KnP6v8mYRj3tfMcsgpXRyz/h8t1H53prS+3SlaQmAPZeOyk1FRuCIMgKA0EQaDv7Wbvjt+EPY0iWyea68swuYpMdu0jYXYEzMpJISxW/wGg0UrZyA1ac3S2y5+HnabeZAqnhV5cLCadQq9WcTThGvTJNsDh5M5eSN4PzIMsiBo0bWeacC1+qKRlvgy9YXd+ej5cGfx9N/uzFuvN7qVSpHiaT1W59Kj5OPlXtv8FCGY93gIYh1aUmh4xu3IOPuox3urk67bpixKdkTt3pdHusckPpJhxSIzDMbv8Kah2dzPHgiABPX5YNnyrr4PjHiS12ToJFIcwvmKea9GLRsA+5OWUde57+kVENu8meJVZBYJUk7LhRSA3R33ksPL5JanIKR3UJGoXKv8+D0KFyIw4/P4/3Oj1V7MKCAipE3k5L5HRclF2TZrbMY8+1k5y69WhcB4bW68TxF3+lamA5aRcAPjKzmDFJ9plQHRGXZh+p5C9JnV8QapWagXU6yLbBdTvydLO+/DL4HQ4/Pw+9xM8iy2xk8cmi+TSVNI6usSvO7JRdriwO9l07KZsqPdNstDt281qyTJ4Yi2Bl9iHHwR12quCOZNYCwGy2UiE0nL8vH5F2UTlYa7dGUxi+hgAS0xLQGDQYrdmoVGq0ar3dDdg58hw67T6K09T0r8+5OxGoc+uNXE46R3iZuvmOnM6iUqlyKrXmLvHcSU/iWuItgkpXxGwWK/c7cfJewg+b26kJzJRRseRO8yqUDM3DavN1rxel5hJBrVbTtlIDFg55n81PfSPtBuCG5AmkbaX6uMvMLu26GsEeSX2SwohLTWTuYfv1XYBeNezzXziibcX6PFG/c37r6GAGKS4tkVqlK0rNxUJqdjq/HtsoNRcZuSfIh4FapaJJaDhT2o/i7Ct/sPSJj2UdbvOoFmAvOs7ducZVmVwoUixWi6zjaLhM6vcHpXaZygyQydsj9/6PAmW8S1FPZpYwPj2JBUf/kpqLheJM5Db38FqH5d3t7shJ9+yT+nj7BHMjKU62qIqrSyKQUynUdhXuXGIE9UObFsmx09ahsyjSBMBN60l6dlq+4+bx+AM0LdfG6aURW6T66OCN8wSVqYRJIlQS7xatdHVxkpSZSu/f3pRVpa3C6sjWJFAoPl5oOYjBdV1L1SvH1shDvLrhe4zmwqepu1ZvTkU/+wJw0iluXzcvnqjfRWTLY8jid+2WURyRZcpm0KJ3ZJdEOlZuRHhp528wr7d9gsXDPspvW8Z+S7NyNaXDOHfnGu/9/bPUXCz8dmyT7GcpKotObCExw7XS2K6wZtRnXHxtSX67NOlPbk5ZS9pH2znywnymdXuGWmXkp+ZtcfQ7ORPltDPquGzukZISgB4yjs2uRCU9bMY37S01AfD6xhkuhWrPPri60KrWN5LvsOqM/ApEUbiTnsSyU/K1WOzERWqyOLWnIAgEBFbgiIPEQWYXC4iEeVchOvmyaLbjxN2DNA5tjSXLfl2uMPK349rkST73/T/uczvjOqE+FbCaXBc7Vqt4Xw7eOIdf6UqYTOL3MBozyJa5qT8s9kefps3sZzkqkyhLBXzW/VmpWaGYUalUzBswRfap0FnO37nGkMXv8d0/y2g1eyL7ClmrTc5Kk/WvkVZ3JTeHhnSKGSAu7R5tZj9TaDKx+LR79Pz1dfbJeJWrgI8dRM44i1aj5ZdB79iFegJ8vXcJe12cYSkMq9Uqmyr5Qcg0G5l/dL3UXGxU9C9L9aCw/FY1sBxlfQJxl8lrUxCPh8vPYn684xe2X3Yc/XY18SZjV0yTmiE3uVxxk5iRwmqZtPruWtc+78Pkqca9KGtTJC6PTLORzvNe4p9r9uePLYkZKTy96gueXTudT3f+xnt//+xQYMw+tEbWb/JBmHFA3nfITlykpIjrSZjNFnxLV2C/g4x9By64ti5U1qM8N5KuoTHcXwtNyk7A3y0AawGJqRzxoKGo1fzq5Pt/2HIzPYZQvwou75PRZBVVWD164wKBZSrZLYsAdr4txcnRGxdYc3ZPflt1Zhe/H9/Mx9sX0GTmWFrPfsah1/iktk+IYp2d4dSty+y5esKldriQ0u8Pi4SMFLt9c6YlpNvfpF3Fx82TFSM+ddnBFSAhPVk083Qs9iJt5zxHl/kvs/LMTlFGTkEQuHAnmieWfCA7AykXYVI9KMxh6Gxsyl2a/jiewYveYfPFg9zLTMFitZCanc6x2AtM+msGlb4cJFt3A+Dl1kNoXbGe1OwytcpUYmpX+30UgNHLPyG1GAX8tstHZDNabn7qG9I+2uZUa1rO/nv+6cAqhyGJjwo1S1ekgcxMptFipuevkxi9bCp7r54gKTOV1Ox0Tt26zBsbZ9Jk5ljZGlQh3oGy+RMcISBwNi5Ktp2+fYW9V0/w1Z5FNJoxRjbSooK//WydHGarRXTddKZdSXgwZ1Evgwez+70hNUNuyHibOc8y8I+32Rp5iHuZKVitVtKNmeyPPs3H2xdQ/euhorwpn+78jQ+3zRdth9xZxLmH10rNPN2sj91x6qhN6zpR+nKO3LggWxhQVHLdbDay+k/xh8zKyqZFlxd5Zstsu1LV5DpUdqrnRrlA+yccOVoEd2Dv1a3o3MVPG30rj+TItX3cyI5CXUA4q5SRNV6gU/nepGYl89SynniH2FdgLIic/fkbnbt4/6v51aaKV03WXVziMBxVyo1b2Ww7lApehnyBoddoSftwG3N/GEvpMuLEKE1bjqBi5QfLxOao5HpR6VK1KetHf4nBwc3OUcn1olClVCiX31gmshW13LazyJVcLyrrn/ySxyV+KXIl1wfVac/yEZ+KbFJ+PfYXTzl4wkOm5LrRbKLrglfYXcjTeRkvf7z0HiRlpZLgYPq9oFLgFquFHr9MkvW3KiqNQ2uw5+mfHDr1unoMWKwW2sx+loPX7S9wTzfrw5z+k6XmfFwpjd37tzfYcGG/yFYjMIzzry122u/sl6N/MXal/e+8ZtRn9K3VTmp2GldLrheFrZGH6PbLa1JzkVgy7COG1e8sNYODkusPygqZMuRyJdeLwre9XuKVNkNFNleOqzzGr/yM+Uc3SM1FZtHQDxjeoGv+3wuPb2L0cvsigidf+o16TkZtxafdo9zn/TBKon9GNOjKH0M/ENlEd/GMdHuPXqtVwNvTn5up4jojeQgC7DydxbHL2WTnRkVcu2FfUwMgwK0M0XdjiTibzs6jqaSk31frJ+IP0rS86yGp+ee0kye3lBxtZT+FdDnpHNVL1cFidP6J4tiZNHDTifbFaDGTnp2Bm7u3XTKtNMks0b/NwNrtWfvkFw6FhULJMaZxL8Y6qFAph0qlcsohLi7tHlcSYx0KC4CPuoyXFRbkFkNaPeozOj1ghEwejUKqs/mpbxwKi6KgUWv4dfA7srM/cw+vY1MxOPNFJcbyl0RY4CDpUEEMrddJtgT9v+XY6QpdqzdnXBPXitbJ0bdmW9nEYiVFmwr16F/L3snzUWNWvzcYWLu91FwketVoKXJsdRR+2iqsjtPCAiDIy5/BdTtKzSw7tZ3bqQkim0hcmGSmS60WK75e/txMkRcXkFNm43S0id1nstl8JJ295+SXSsrqq/Ptqn2cu6siOlmFrYtFdOplKvpVc9mpM79gmQsneB7lvSoTk3JF9uIgIJBqSsbX4OdUgq99R1K4l60GSTZPgLiUBDy9/OzERVa2fezwv0Gghy8LB7/H8hGfuLwWq1B8zOw7SdZzXA6dRsusfm+wZtRnVPCzz5nhLK+2HsqEQso6e+rd+WvMdKa0H/VAmQMnNO3DzgkzS6QgU42gCnzS9WmpGXKzVD6o0+SPB1bZPYK4afWMbmyfdKggPPRujJZJVLT9yjHOOQhZfZSY1e8NRjboJjU7Tc8aLVk87EPZa25J0LpCXVaM+NRu2ftRRKfRsvSJj/ig01iXcoBImdRmGGtGfY6bzbX80PWzsv51cgneCuOZ5vZFCE1Wi92Si1hcmOxnHNQaPQKQUkihI4CbiRbiUsGqtf9iYm9nc/ZyFllqbf4NWHofTsyOJ8AzCMElJ9H8qQuJvXBCvSpw/d5Vkf+HLfcTfDmevbBYBPYdSeHyHQu4yS8N3UyJx9PLH4vEf0NOzD1MKvoF80mXCVyctJRRjbo/tBNeQR53nYEVIz7FWy+ftU+KSqWib612nHt1MR93Hk+Id6B0iEN8DB78Ougdvu71olO/u0GrZ1q3Zzj8/Dw6OAgBdUTj0Br8Pe475g6YLJsvobh4pfUQWoXVkZq5lZrAC+u+lpqdJt2YyQKZ6eph9Trj7+44fNMRE2UuzkCxO4uWBDqNloVD3mPJsI9knRAd4e/uzZz+b7L+yS+LddbKEWG+Zfih9yvsmjCTMt4lX6ejuNBqtHzYeRyHn58nW0m5IBqH1mDbuO+Z3utFtBJHbLlZiwAPHwZJloqcoXWFetSRiTCafWiNKGJN5HNxPTqCg/t+ze8EMJl1dOz7JmW/cE3heLmpwGpFyF068dJ50SikNpvP7Qd9zgevWlZLm1r3D7R6AU3x1wax7epadB7y07RSRoe/TPtyPckwpvPk0q4u+VyU96rM1buRaB2IAr3awLhak/h27/u4+dufEIIgsP9YKpduW0DiQ2LLsiEf4HvrEnG3TuPmdl9NBpcNp23HB4vKuJVy1+mqmnqNlmCvAOqXrUr9stWoXaaSUzcWW64nxfHGph+l5iJRxsuf73u/KrJdSbjBO1vnimzkhiE2kQk7dJWp239x6MjqKm+2G2GXBOr9v38m8u51ka15+Vq82maYyFYQ68/vY5EkxG9I3Y4MqFPwlKnZYmbvtZNsjjzE6dtXOBMXRWxKPFZBwKDREejpS5uK9emZO2XqKPWwM5y5HcXik1s5fP0cETcjRamEfQweNChbjcah4Qyp15Hm5Wu7dJw9yDEQGR/D+9vmSc2Q67dSLbC8yObM2vihmLOya/NvPTaSBg6SIBXG5E0/EZ0kjszz0rszt//kIj1lH4w5w3f/iP2XAL7o/pzTzoyukm02suniQZaf3sGp25eJvHs9fy1er9FSLaA8tctUold4K5eOt51XjjFHxvHQESrATWvA2+BBneDKtAyrQ50ylQs95hYe31Qs+S+ebNidnpLIF2eOK2eIuBnJ4hN555k4y62bVk+t0hVpU7EeA2q3p12lBrKf2Wg2MX7VZ3Z+Eu0rNeSZIsxcAKw6s4tlp+1DUN9u/2T+MotIXFy9fICjh5bajsVicaPN469Q/qtBIrur9K/Vjs3nDpBpyQbN/ZOndpiOhpX1aDUqtCodT9eZzNd73sVd5mYux5iaL/NYaE8yTemMWuKauHCGZ+u+zcx/PkXtbRP2msuJc+mcuJwNnvZrvbYsHvweQXeiuXkjAnf3++IiqExV2nd+OImUFP67WK3WIt2wnEUQBFKzMzBaTOg0Wrz1HiX6fgqPJlarlSyzEQEBN62+RLKj/pexWq2kZKdjtlowaHV46twf6fNMtGeOYmMd2V3BQ+9GpjFTJCwAzsaYWHUgg/MxRjKMRqyCBYPW3en3VOV/BHvFVhycTThOg9Bmdo6dSSlmTpxPBydmWKwO4ooFB5UnFRSKk5K+AKlUKnzcPAn09MPXzavE30/h0UStVuOhd8NT764IixJArVbj5+5NoKcf3gbPR/48E+2dWiZhjoD1gZxLAAwaHVkm+RShABnZAocuGflzXzqrTh+inGdjMlILzzZoiyuFqlwhL8GXbbbObKOVAxGp4KF3KkpFr9ZiFax2Q7Uy3u0KCgoKCgr/64juyBqZTHcWsxH3B3TAeaxyQ3ZfPgaFKC2LFX49tIcq/i1YvjuNc9cdC5I87i9VFH6TLwopxiR8DH6Qqy3uJZtZvjGBOKM233ekMDz0bphN2Xb7qJVJU6ugoKCgoPC/jsjnIu7WBfbsmCUakJqazqjxs/D6sLOdQ4izjGjQlUWHNzp9M1476nP6z34Nq6eega088HZ3LErG1ZpEm5CuGC3ZDF/UEa+ynna+EQ9Kr4pDORMbQVTGebJMsHxjAvg755wEEPHcPC7v+xNj9h10uvsCrlKVFjRp8WAJsARBYPeFPdxLv2czM2L/+XMsYrv812RjFP3TfrD49ZJty9jkN60CVd4haDu+8H0V7VMh/Xn/Uuf+Q6US7i+o5dlsxtna7o/L2U+V7XZsxudVt5HbDhT2fvdfm4d42/f/ndN3f9nQ1pY/Lr/X5rU2Btt9zUHI/8NuvM175NgLX7KU/l75f9q+VDIGm/0vjILGFaXPkV1K3ue6f9UUHH/WAsj7vfOR+Uql283D3mxzLIjshSP3HipB7nrr3G8jtz1RwaXcfrlhOLTLfDky5B+XqoJfkr+PBYzB0WeRxWZg3jbzTfYbEQR7m3icfb/0bL2P3G8lRe51920FHz1yNvLtotNZpUMb2BqVxj3nb1txkZgQw/bN4pCt9PRMHh/6KU1mTyTahRK7tgyr14mlR7c4LS6mtB/F7vNHuGWOpF199wLFwrhar9MmpAsmi5EnFnUoEXER4hlGqzKdWXRyNka1hpWbXBMXtyavZsvyTzEYLGg095eYqoe3p37jonnrAly6fYkZW2cSeTunwur9j60S/Tv/v/nGnP+rVaIX5fflj7Lpy/u37Wi5/vz3y3nD/P4cm/z4+xdaW5v0tff787py9lRss/08+anhVZD3ree5/GhUAnlHo0ad8/5qQJP78rxxaoT7ttz91KgENLnvk2dTq3LG5tjun/J521bJbCfnNTmo1Tn+N2ob4ZK3PbVKdf/fefulElDlnrp5No3NDeC++Ll/88s/8lQ5r0d0abLYjVOp7LdH7jZz/p/7t01f3uXGdjw2Y+XExf2h9jcwtcq+GKDK7j3v71POv+3J31dbW94fgr1AoJDX2IoL6YSsrW6Q+27I/f1E3Nd2+cjvk3D/3MjdCTmhKYdK5ruxFTn5n1ewv06rZL6jnD/Fn0M6htzX5v87t1+lsn3p/W3Lfl0ywhuVvb9a/nEp2nZen82/8/6Q+c5tsfuNRIi2mP///I+a/yb248Tiwua1dkfc/XE5fdK9VeWfreJfUTzO8Wvz9sfelkehr5XYVDo/9GEj0AW0EouL7Kw01q18J384QGZmNm17vMaIdV9zQJLW2CWsgv0VxwF1ylRiZP1uvLNhBiO6+xWYIGt8rddpHdIFk8XEE4val4i4AHi5/kd8vnMyJp2WVVsSnRYXKiB76i5+njmewEBf0b7VbdCb8NryKXCdQRAEBOlZpFDiFP/RpaCgoPD/B5VKLZ5T0Rs80elzpjTy0GjUpKbcpXKpEJHdZZwUFgBn4q5SO7gyFqOVU9dMnL+Wxfmr9gm+gPtP1CUgKGy5nRFLiG8YmVkWlz5Led8ypGWm5qpz8et8fB8s/lylUqFWqZX2kJtKaUpTmtKU5rAhmhXNvVl5e5e2NaHVakiJj6aZTNXEkiQq8SZVgspx4nI2h66YORRlJindfios7zlSziegOImI30/TsDYcj0jJqR/iJE3KhXPrdhQ6rf1Uo7eP+LtWUFBQUFD4/4CdN4j0hqdWq0mMj6ZluVoie0mz/sI+etd/DEz3Q0A3H8/EIqnz8bBmLi4lnaNGQF0SE4x2uToKomloOMl3rqGV5DpXqdR4ejmfPvffxmwxczXxJpfuXidJpqTxo0S22cidtHskZqRgKqIT8v9XBEHgRvIdIuNjuJ2a4HQ+mUeJu+lJXLp7neh7t+3q9fwvk5CenP+5HvUS7Ar/LVKy0rl09zpRibFOX1NFPhcAF85u4/SJ9bYmMjLNDB41HZ+PumJxkBCquNGpNfz5xFQGzJ0EnvezWnZt6EZIqfuzABPrvEWL4A4IgsDg39uUmM8FwIgqrzD862nEe1nkPZdk2D32e5LP7CQpMQo3t/t5LXx8g+n2+BTR2KLw44GVfC+T9lelUuGld6e0lz+D6nRgSL2OeBtcq+tgtVpZc24PP+xfzuHr58g03w8NrhoQypC6nXi59RBKe/mLXucKh6+fY8SfH0rNBTKt2zOylfnWndvL/KMb2BJ5iGxLTp4UnVpDzxqtGNmwG4+HtxIV87l89wY9f51kswXnGNmwG+93Gis159N9wavsuHKMl1oNZnov5zKwHow5w5PLpkrNkFtzxN/dmy5VmzK6cU/K+bo+43X4+jm+2rOIHVeOiVJ1B3uVolv15rzZbgS1ZOoFOIvFaqHmN8OlZgD0Gh2+bp40Dg1nbJNeRUqZHZN0m+l7lrD23F5iku87lnvrPWhdsS6vth5Kl2rNHujcH7r4PSJuRkrN+bhp9VQLLE+/Wu14vGYrh3VF8lI/O5PqOTY5nq/3LmH12d1cs0kH7qV3p1WFurzSegjdq7d4oM81etlUWX85jVqNj8GTSqVCGNWwO92qNbOrSSHl5K1LDFok9ssrjPc7jmVUo+5Sc5HoOv8Vrt67ydax31HJiaX6SX/NYMb+5XSu2pSNTzlXXyYxI4UWP03ATatn/eivnEqfHnEzkqGL36NDlUbM6T9Z1Lfu3F4mbZwhshXG/IFv005SW8TRcbX23B7e2Oi4JINGraaUuw9dqzVjQJ321HWyOOK9zBRm7l/J4pNbuRgfk+/dZ9DoaBxag+daDGBovU4Ojxk7cZFw9xo7tnxrayIjI5NOfd9h4PKpHL5xXtRXkvwx5H1eWPoZSSpj/s28TgUdTarev0E8U2cKzYNzai4MWtgar2BPVC74RDhLeoaF8prm3EvQ8svJzU5Fvhg0OuLf2cCfv7yOl5cOjc2MR5VqrWnUbIhofFGYuv0X3t82D7VKJUp2ZhUEzDZPPx46A4PqdOCLHs8R7ETBodO3rzBk8btciI8BoJJ/WWoEhaFVa7idmphfYc9dq+eDzuOY/NhIyRacY3dUBO1/fgG1SoWnTuzv44iZfV/jSZvKklarlbc2z+KrvYsBqBlUgeqBYRgtJk7cusSt3FLAwV6l+G3wu3St3hyA83eu0eCH0fnbycNitWIRrKhyCzVJea7FAL59/GWpGYATNyNpOOMpyL1BXH9rNX7u3tJhduy8coyO816C3LoMeQiCgMnmd1SrVHSp2pSpXZ6mafmC62wAJGWmMmzJ+2y5dBhyixU1DKmOh86NpMxUDl4/mx9iPqJBV+YPnIKhCMndLFYL2nfagWT/AUwWs8jtuEHZakx+bCTD6hfuzGy1Wnl940xmHFiB2WpBr9HSonxt/Ny9yTBlEXEzMr+cfNNy4awa+VmRxBdAq1kTORBzBq1aY+dELv0dSnv6sXrU57SqUFc0jgJuArYIgsCULbP4Zu9STFYLOrWGFmF18Hf3JtOUzYlbl4hPTwKgYdlqrBr1GRX9y0o34xSdfn6RHVHH7T6X2WrBanP5L+sdwLgmj/N+p7Gyxz25IrX5TxNcOl+/6vm8w2JtrlLj62FE3r3OxdeWUD0oTNot4l5mCuU/6096bkHOky/95lR58fi0e5T+NKe0fOPQGuybOEv0UCLHgejTtJr9DI+Ht2L96K9EfYsitjBy2cdo1RrctQVvJ4+VIz+lS7VmIpuj4+qPiM2MWjbV4fVKev690XY4n3V/psAsqj8dWMXkzT+Rlltcs3n5WpT29MdoMXH+TnS+wK/kX5Ylwz6ieVhtyRZkxIXVamHt8imYzffLppvNFirX6MzOzBSmbJ1jO7xEGdGgKxajiaUnt+WXUG1Rw0B4ufs+Dw9LXFy7kcWRU2bmj/6IYfOnFFpPhNzywt93HMv2NV9SKsBX1Ney7VOUC3Ot6p0ceeJiapcJvNtxjKgv22zkbNxVFhzdwB8RW0jOTqdaQDm2j/+B8gWU6Y6Mj6Hd3OeIS7tHx8qNmNT2CbpXbyFKN3s2Loof9i/nl6N/YbJa+KrH87zeTv7JtSDyxEWXqk3ZOu47abdTLDu1naFL3qe8b2mWDZ9KC5vKmBarhW2XjzLr4GrWnt/L8y0GMLNvwbMVf13Yz+O/vUGvGi3ZMGa6tLtARv35MX+c2EKT0HCOxl7gyx7P8Ua7EdJhduSJi27VmrF5rFjcmy1mbqTE8/vxzcw/up7opDi89O6sH/0l7QuoUJqWnUHXBa9yIOYM4UFhTGr7BCMadMPd5kIZl5rI7EOrmXFgBQkZKQys3Z6lT3zk8GnEEXniwkNnIP1jcUEjq9VKYmYKa87t4efD6/IfUL7p9WKBBd0EQeCl9d8y88BKAjx8eLHlIJ5p3l9U5TLTlM2iE1v4eu8SLsTHUCMwjD0TfyrSbFqeuDj6wnway/iYZZuN/BN9mh8PrGTV2d3oNVoOPvczDSUzMY5uAnkIgsCbm35k+t4l+Ll58ULLgTzboj8hPkH5Y7JM2Sw9tY2v9y7hTNxVKpcKYe/En0RjnCVPXOyd+BNtKtbPtwuCQIYpiz1XTzDvyHrWnd+H2Wqhb822/Dn8Y1mRmScu2lSox95nxDmRHgauiIsvdv/BW5tn5Z+Loxv14NfB70qH2WErLgCeatyT+QPfLnD2yBlx8VTjniwY5Nqsjy2Ojqs8cTG2cS/mD3pb1Efu73zp7nXWnd/Hh9vmk27K4oWWA5nR5zXpUADmHFrDM2u+wqDRMaFZH15sOUj0XVusFtaf/4ev9y5hX/Qp/N292TVhpp1ws3MeUKs1BJYWT5totRpuXDvB4NqPiewlzcaLB+hRq7XI70K6Rmz7g5ekU2dquoV0czZqtRp3mZNOjgE123HzynEMBvvxQWWqSU3FjkGrp1FoDWb2nUTs22vpWq0ZlxJu0HbOs0QlxkqHQ27V087zXyYu7R4TmvZh2/gf6Bneyi6Pfe0ylZnTfzJ/Dp+KRqXmjU0/8rMLlQyLk6/25MxYzB84RSQsADRqDd2qN2fNk5+zeuRnfO3kMkVRuJF8h6WntlEtoBwrR36KVq3h+3+WicoQFwWtRktF/7K81+kpot5YwZT2o0gzZtLjl0lsvnhQOhxyb4T9fn+LAzFnaFauJoefn8f4pn1EwgKgjHcpPug8jv3PzCHI04+VZ3cxftXndufZg6BWqwn09GN80z4cen4eq0ZOQ6fW8NpfM/h0h7gKsy3vbp3LzAMrCfTwZe/EWXzQeZxd+Wx3nYHxTftw5Pn5tChfm4t3Y+g6/xWSs9JE44oDg1ZPxyqNWTHiU55vMQCjxcwXu/+QDiuUT3f+li8sdj/9I1O7Pm0nGtx0BsY07sXh5+fTrmJ9ohJv0mX+KySkJ4vGPQgqlQpPvTs9arRk5chpnH91MWG+ZVh7fi99Fk4m03T/AfN/DaPZxA//LMdDZ2D96C8p6x3A4hNbuZkSLx3qkDJe/pT1DuCXYxuZ+y9d24oDlUpF9aAwXm83nH3PzEKjUjP38FpupdyVDmXJib95ds1X6NQa1oz6nBl9XrMTcRq1hn6127H76R8Z2aAb9zJT6TL/ZS7fvSEaZycuAErL3PhSkmLxd/OiuqRksS1tKtRjymMjmdKueNozTfvSrHxNpnQazZR2I2kbVherRSIubASFVFmWcguiZ4Wh9Cw/5IHbiDrDmdJ5DD56D74dOIkpbUYwol6XnJzlMqhVKvrUbM21qOMYJNElfv6hGFz0f3hQPPXurBn1Od2qNSM6Kc7hGt3UHb9yPfkOA2u3Z1a/1+2+Uyn9az/G/IE5viOvb5xJeu402sPkQnw0QIFP8QD9areTfRorLn74Zzlmq4VX2wwlzC+YIXU7Eptyl2Wnt0uHFhm1Ws2nXSfyTofRZJmNjFv5mayD1Z+ntrP9yjHCg8LYOObrQv1tqgeFsWXst3jrPfjt+CYOXz8nHVJs9K/9GCtzBca7f//MhTs5v58tVxJuMG3XQjx0BjaP/YaapStKh4jwMniw8anp1C5diZO3L5fozUClUuXPEq44vdMl58sbyXf4YNs8DBodG8dMt3vak+KuM7B+9Fc0KFuNc3eu8ePBldIhxUbVwHLsnvgjFfzKsPXSYeYdWScd8j/D0lPbuJl6lzGNexLsHcCLLQdhslqYsX+FdKhD/Ny8WT78E7RqDS+u+4ZDMWelQ/7naBBSnX612mG0mFl7bq+oL9ts5MX13yAAfwz9gO41Woj6pajVahYMepvHw1txJz2Jj7YvEPeL/sqlXNj9qbM8DG56Ll88wPjG96eLpLjrDEzr/izTehRfCy9dkWl9XmBaj2cxZIM5S3ohtb35iW+EJouRnhWHMLjGuAdurz72HNP6vEC3Gi2Y2HoA03o9R7hvKGTKP5X2rNGS9NRE0tMS0ErCUEPK2a/TPgzcdQYWDnk/R5We20OMjQMZudPoS07+DbnrpAWtydkyunFPmoSGk5KdwYrTO6XdJY5H7tP4qduXpV0PjZSsdOYcXkOAhw+jG/UE4NU2QwGYvmdJsc4EqFQqpnaZQJ0ylbiZepc15/ZIhzDvSI5T9rsdxhDgKV6Sc0TDkOqMa5pzfue9vqToXbMN45v2AZC9YS44+hcAoxp2l12ikMPf3YepXSdA7v4X53cuJdg7AA+dAYtgdekJ/9djG7EKAsPqd6aljL+GHD5unkzrNhGABUc3lGiETEX/snzf+xUAZh5YWaLvVVIIgsD0PYtRAa+2zll2m9i8Hx46A7MPrSE1O136Eoe0rliPb3u9hMlqYeCit7mTdk865H+OSqVyfHdSjRki+5qze0jISKFlWB2G1Osk6nOETqPl2145/mcrzuwURRLKigtPrwACgyqLbDqdlivndjOuyeO4OXj6+/vyEZr9OI6VJ3eQXUAVVFe5l57C++t+YtulI+g9xbMAjqUFpJqSef/gM2yJWkWasfjCJ41mE0sOb+KzzQvAXT7nxastBxN5chseHvYOPBUrix11HialvfzpX/sxrILAnEPip7tlp3eQZsykY+VGTnli2zK2SS8A5h/dIO0qcfIiR8Ys/4RLd69Lux8K846sIyU7g2eb98cjt9Bfk3I1aVexPidvX2b7laPSlzwQKpWKp5v1BWCm5GnsYnw0e6+dxNfgyYA6Of5IzjKuSW/IffJLyxZffIqbp5vliItfj20kJev+Bd9sMfPLsRxxMbaJ44cZOXrVaEWQpx+Rd6/zT/QpaXexEZUYS4YpGz83LzycLEBotVqZnyvaXP1cXas1o5xPENFJccV+LEnpVaMVId6BRN69XuLvVRL8fekwp+Oi6FurLVUDywFQysOHMY17kpSVli9cneX5lgMZ1bAbsSl3Gbr4PcwyM4X/S5yJiwIgVLIUN+9o3rGZcy13lqqB5XisUgOyzEYWn8h5OMWRuACoUKmp1ITJlMqd21d4ogAv7yM3LjBo6XsETe3JqEUf8O3OxXy7Y5HTbdnx+zv3+8EN9Jz5AmXf687UPQvBxw0fD/Eu52UDy/m3VF5AYnY8S6Pm8PLeIXx28HX+urSMvy461w5e3yXa1v4rJxix4G1C3u3O8KUfkuGhks15UT2wPI1CqnHl8mHc3MTiIrB0lX89v8WIBl0B7C4c2y4fgdxpa1fJu8HvvXaySCdfttlIXGpioS3bJhw2jzcfG0HlUiGcibtKzW+G0/OXSfx2bCPX7t0q0afXPEwWM9/9swy9RsvzLQeK+ia1zSlMNz3XL6Q4GdGgGwB7rp0ULY1sv3wMgO41Wtj5WBRGneDKhAeFkWbM5HgBYZnFQYOQ6tQqXZE0Y2Z+9BHA+fhobqUmEOoTSNNyhUfE2KLX6uhfOydqZVdUhLS7WLBYLbyzJcex/clG3e38kRwRlXiTa0m3CfDwoa2NY6UzaNQaBtTJOS9L6nPlodVoGZr75Cq9RuRhtJjszk25Jne+ljTT9y4Bm3Mvj5dbDUEFfLtvqUvXKJVKxex+b1I/uCq7rkbw1uaiObJmmrLtvh+55sq+ucrOK8fYHHkIH4MHfWu1zbdbrVZ2XMm5bvSvVfTr/66rx/NtDs+KcmENUEumxd3c9Fw6vYM3Ww+zmyWQkmrK5NCtC/h6euPr7uV0S8vOYMH+tSz4Zw0fb/yZTdeOkm1Q5UeLbDuZxcIdaSzcnsquU5mIc2qp7ArW5GEVrESmncbLwxsPnadTLdOUzh/7V7Ng32oW/LOGaZsXsPjUNhJUWWDQOsx18VqrIVw4swu9TmN34akoI9oeNiE+gQAkZYqd3vL+LoqnfYCHL5pcoZdShCfePddOEjytd6Ft3zX7p9Ewv2AOPzePkQ26oVGr2RR5kDErPqXSl4MI+7w/z62ZzunbV6QvKzaWn97B9eQ7jGzQzS7M9/Hw1lQNCGXLpcOculW8yzalPHwwaHJmzmynI5Oycv5d2tP13xEgOFf8PoxkafePRZv9z/13kKe/7ANDYZTU/mebjWyNPES3Ba+y9NR2qpQKdSkEO+93CfTwe7DPlbudkqSsT953KO8Ye/jGebtzU65tzQ2BflicvHUpZwa9XE1aV6gn6qseFEbvmm2ITopj5Rnxg2NheOjdWDVqGv7u3ny9bynLTrnuR7X01Ha770euXU6Qd7YvKoIgcDE+mo+3L6DbglcB+O7xV/C0KfWRaszAKgioVSpKecjnbymI4FxH62SbGUiH4kJv8CCsYmORTaVSkXDnEm4WM8Nzn34L4lLCDcat/pxx6750ra3/knEbvuKy6W6+qMhDEHJqoFlRcS3eQnLafTUhjU2X49fz37Ew6odC24e7v6T3rA8ZteZLxv01nXEbvuKvG8ccLoPkUTUglGH1OnHm+FY8PMTTpTqdO+UqNBTZ/g0sueuoOpsKreQmWyE3/t1VBEHAmptgTbpdZwjw8KFnjZaFtgAHB36Apy+/D32fm1PW8VPfSQyu24EQ70BupMQz69Bq6n3/JE8sed+l9XFnyFvfBWTDKtVqdf667zf7lkq7HwhBEPKT2tnGt+f5yhTldwRkt1lS3D8W5fa/aE9wD7r/j815Ht8Pu4ia9wed8Xi/I91+eY3tV47Rp2Ybdk6YYRflURDF9ruoi/a5XEHud7HFz83L7tyUa0UVuEXl69xZi9faDJMVcK/lnqNf7V3s8qxm5VKhLB76ISpg7IppnM1dXnCWUJ9Au+9HrnnmLqu6ysKIzXbHrc8HXXB/rwPh3wzng23zCfEJZOmwj3hKsvSR92BotbmOu0L+8WIzIeFQXACyFTvdPdw4vn85X3SdmP/U9G8iPn7sD6bCyMi0EHU9i30RaazalczKfWms3JvKPxeNpGt0ssseBfFl12c5fXwTKpUJrVZ8k61Wox06J9dnS5IruWGogR5+InuAR47j35UiKOfYlHiE3MRhXnrnKsba0iikBn+NmV5oKyy7Y4CnL8+2GMCy4Z9wY8oazrzyO2+2G4Gnzo2lp7bT//e3pC95IHZFHSfi1iW6VWtGnWCxn1Ieoxv3wN/dm8UnthKb7HwoXGFcT47LTyzlYxMNkifA8n5nVxAEgeh7OY6+0uOjuLFarfkh0YG5xx42+3896U6Rwnjz99+zaPtfxrsU5X3LiJpVsGIVBHqHt+bsK3+w9skvCswVI0fe57qVepcMo3whxoJ40M/lClGJN0Hyu9hSp0xlu3NTrsklVyopbiTfYcnJbVTwK8NAB75G7So1oFFIdY7FXmTP1RPS7kLpXqMFH3eZQLopi/6/T3Ep5LlrtWZ2349cc/W4ysNL72533Pq6eZJtMeGt92D1yM+49Poyhsq4NXjq3fOT311NvCXtLpTo3OAA22OzwDunt08Zu0RParWK1OTrpNy9wfMtxOvL/wYZNg+iKpXKqRLkFovA5ehMDpxMY8vhdPacM3I5EVIsGlKzIdWowqJSS5VLoTQvX4t2FepyJmIrnp7i7HVarZ5q4a6vZZUEeU5l0gyJeWtwv0dsdlnV/xGxBYABdR6TfWL4N1CpVNQuU5kvejzHwed+xlPnxpZLhzlms77/oOSt716Ij6b1rImyrev8HO97k9XCjAPLJVsoOvOP5DjPDqnbSbT81rNGSzQqNdsuH3FZzOy7dpKY5Dgq+JWhcWgNaXexsiPqGNFJcVT0C6ZZ+fu1i6oHhlEjMIzk7HTWnd8nek1hpGVnsPrsboB83wtXWTZ8Kmde/UPUFg3NSVG/KyoCfREfqsr7lqFB2WpkmLJZdda1aflMUzYrzuREYjm6cRYXadkZOYkLgaH17G9E/yYFXZdm7M/J4pphyuaxuc/bnYetZ02kzexniEtLBGB6bkZfV3m7/ZP0qdmGSwk3GL3sk0cmomZA7cfsjttzry2iemB5Uo0ZnLp92eFMlEqlyr/+L4zYJO0uEEEQ+P34ZpAcmwWKC4CatbtITbi7GzhxYBnvd3iSagE53rj/FqI8F07OXFyJyWLfiXQu3oVksxq0hX4NheKm1fP7wHc4vHcJBoNGlOoboEr1tugLyTXwMLgYH82OqOP4GDzyHTvzeDy8NaU9/biUcIO9106K+gpCEAQWHMu50U3IDS981KgTXDn/wD8QbV9noSicjYti48UDAEQnxbE/5ozDdi93/X/2QddC4RxhNJuYn+vd/XzLAaK+EJ8geoW3wioI/HZ8o6ivMPI86cc16W3nL1TczDq4GoDnWg4QhT2rVCrGN82JWsn7jM6y/PRO0k1ZdK7ahMqlQqXdRaZf7Xa83GowqcYMhix+l6wiLK+JPleuMHSWNWf3kJSVRusKdQvN+fGgLD75N6nGDDpVaUx46QrS7n+VrFwHUamjckpWOrMP5RxP8elJduefbYvNTR614cJ+zt+5JtqOM6jVahYOeY9qAeVYe34vn+/+XTrkkcHb4Mmy4VMxaHR8uG1+vtOmHONzI8V+OfqXS7lbjt+8yOm4KEK8A+lR/X5ujEKvHn6lylFe4iegUqmwWtKIOLiapUM+ENW0eNiIn5ILFxfXb2Zz6HQ6yISIPghfdXuW7MSbREcdtZu10OncqVHTvtDWw+ZG8h16//Ym5IbCeRnEyxc6jZYxjXPW4sav/MzpmO4pW2ZxOSGWqgGhhSayKgku3b1e4BNNHm66nBBqR+rdVb7Zm+NDMaf/m1in7Su0PVG/M8nZ6S7fWKRkm40MWvQOsSl3aRIaTvPy9lPPeTexaTsXclCmaJUca87uYWHEJjQqtd2abHEzdfsvrDq7Gw+dgbEyuXOebNQDnVrD5shDzDq4StotS2R8DJM3/wQlJHK/7PE8TULDibh1idf+cq0QVR7DG3TBTatn19UIvnXSB+dq4s38wlcl8bls2XnlGK9u+B6AF1sNknaXOBE3Ix2eyzeS73A9+Q6eOjeCJEtD84+uJyU7g5daDbI77+TaJ11y8qHkncOu4uvmxaqRn+Gpc+PdrXPza/c8itQvW43ve7+CAAxf+gG3c2stSelctSkV/MpwIyWeF9Z94/B3sCUpM5WxK6ZBbgirbdmAQsUFQP1G/dBKclvo9TqiLu3Dy5zNe+3tiz+VFD8PmMz1yavyW6cq951Ov++7mG/aLmJ6q9+Z3up3zKlWBJtwkgtXMth+JA2LpxsUY/2RzlWb8ETdDhzc8Rs+Pl52ywJ1GzyOwc1LZHvYHI+9SPu5L3Ap4Qa9arTks27PSIcA8F7HMbQoX5tLCTfotuBVEnOLQskhCAKf7/qdL3YvwtfgybLhn9h99pLmYMwZ6n43iufWTi9wRiApM5UVp3eiVqnoaHPMFJVbKXf548QWgjz9eLJhd1QqVaEtz7Hz231/Fjnc7EbyHfr/PoX1F/6hakAoK0d+KvudPx7emmea9yPdlEWPXyZx8tYl6RAR2y4fYeiS97AKAgsGvV3k4l+FkZKVzlubf+L9bfPw1LmxfvRXskm+Snv5s2DQ26iA59d+zR8ROdOujohJuk2X+a8Qn57EhKZ9ZKvmPih6rY4/h3+Mj8GDWYdW82fu0oEr+Lv7sHDIe6hVKl77a0b+EqUjbqbE03n+y9xKTWBUw26Malg81UWlWKwWlp3aTq9fXyfDlM3ULhPoW6toy0pFZcmJv2k6cxxf7Vkke2ObfWgN5M4i2RYSM1nMfLdvGWqVildaD7U77+TaM837467VszBik8ObbWHUCa7MgkFvIwAfS7JTPmo83awvQ+t1Ii7tHsOXfig7M6FWq1n6xMd46tyYfWgNb2+ZLfs75JGWnUGvX1/n1O0rtK/UkLc7iHWAU+LC3cOPWnXvV6HMw8vLg4M7fuHFlgNobrNmWpJcjI/h4LUzHIw6xcGoU2w4vYcVx/9mxfG/iYw/TWT82fxmyjCKQlMvRuWGkBYj/u7e/D7oXfZunYdGa0WnE2/fv1QYlau2EtlKgtiUeI7eOJ/fDl8/x/bLR5mxfzmNfhhD45ljuZIYy8Da7Vk18jOHVf7y0ijXC67CiVuXqPTlQCb9NYNr9+47+WSbjSw8vonGM55iypbZeOgM/DVmul0BJ1dIzc7g1K3LTjXbi4FVEPBz92L2oTWETuvHS+u+JTK3kiu5ywdbIg/RctbTJGamMqxeZ6oVkMLeWWYeWInRYub5FgMcfpdSmpavSZsK9YhJjmOFg1C45Kx00e945Pp5dkdF8EfEZnr88hphn/dnU+RBapWuyJ6nfyLMT74ctEql4sc+kxjZoBtJWWk0njGWYUve51DM2fwLhiAIbL98lN6/vUGX+a9gtJiZ2UdccdZVLFaraP+P3jjPvmsnWXtuD08t/5Sy03rzxe5F+Bg82DL22wKF3siG3fmp7+sIwKhlU2k35zlWndklujCei7vKxNVfEP71E8Qkx/FE/c5Opa0vKpVLhbIgtzjUhFVfFClp2+C6HZk3ICdl/vhVn9Nq1kSWndouEpwX46N5fu10qk0fSlTiTfrXaseCgW8/0FLVhfho0e9yMOYMWyIP8e7WuVT4YgBDl7xPptnI1z1fsCuCKCXdmGl3XjpqztbzqJq7xD558yz6LpxM9L3bCILAvcwUPtnxK5/u/A21TfK4PFac3klMchwDaj/mdPK/AE9fRjfuidFi5scD9hlinWVIvU5MajPMCU8/SMxItftuHLXirCFD7vVgbv/JVA0IZWfUcaY6qOnTIqwO60Z/iUGj4/Pdf1D72xHMPbxW5IAcmxzPO1vmUPHLgezPrV20bvQXdktVdlVRHWG1Wvh741ekJIs9Sc1mM77+1ajdejBNZz2dXya4pJFWhpMyaGFrvEPEswWrtySQLGjtwluLikalZs2IaZTJTCXiwHL8/L3tLmqdu7+Of8CD38wckVcVtTDaVKjH2CaPM6phN6cqXsalJvLaXz+w9NS2/LLMnjo3DFodSVlp+bbm5WsxvecLomqLrpBXFdUV3u0wmqldn87/+0byHabtXMiiE1vyc2wYNDq8DR6kZmeQbcmJOBjZoBtzB0y2OwmkFFYVNS07g7AvBpBhzCLmrdUu5QVZdWYXAxe9Q6OQ6hx9YUH+8WJbcr0gqgWUY1zT3kxo2sepeHSzxcz72+Yxc//K/HS/Bo0OL4M7KVnp+WXEK/iV4aPO4xndOCd1uavYllwviAAPH0Y17M6zzfvbFURyxMLjm3j/75+JTsop86xRqfF18yTTlE1m7hq8t96DF1oN5KPO44u87FVYVVRbXlj7NT8eXEX94KocfG6uSGA6ql4pZenJbbyzdU5+ZEbe58oyG8nI9enw1LnxTPN+fNptYpHr4uRVRS0IXW4xqonN+tGpahNpdz55VVFdYVKbYUx3smDg35cO89SKT/P9IrRqTX7orgpYOOQ9RtrM3giCQJOZYzl+M5IDz86xK1xYEBfjown/Zjil3L2JeWt1ft6HvKqoNQLDuDApx2G7IMwWM13mv8KuqxEFVkV1hVl9X+eZFv1FNkfHVWFVUW2JuBlJi58mYLKY2TruOzpXlc+7tPPKMSb9NYOI3BlPVe5SkNlqyS/DrlVreLJhd77q+YLstchpcQGQlHiD7Vu+wSqZUkk2puNXvw21Q9ry2LyXHprAAPi051C6VGuI1WphxrGP0RWQh2LlpgRSVcUjLjQqNUuGvE99nyB2bpyBn6+H3VNFeO0u1G1gv55cnKw7t5fVZ+1rS6hU4G3woLSnP4PqdqBGUNEcs6ISY5l7eC0HY85y6e4NLIKFYK8AmparyfAGXWhfuZGdoHKFC3eiXa4s2btma9m01unGTJaf3sHiE38Tl5ZIujELT70bj1VqSP/a7Zze15O3LvHdvmXUL1uVV3Lrg9hy+Po5Zh1cTcOQ6rzUerC0u0AsVgsvrvuWTFM2n3R9mlDfnDwJ5+9c48vdi6TDAfDUu+Hn7k23as1oU7G+U59BSlJmKvOOrGf31QhO375CpikbP3dvGoVUp2eNVgyr37nIN2Vyw0rHrfxMagbAoNXh5+5F49Bw+tRsU6SbpMli5s9T2/jrwn6O34wkKTMVN62BusGVeaxyQyY07YOfu7f0ZS7x6Y5fuZwQywedx1LRP6f+giOyTNm5hfqyGFqvk6jIk6ObgBxmi5kVZ3ax/vw+jsVe5F5mCgatnjplKtOuUgMmNO0ju2zkCl/u/oPzMsXhNGo1vm5eVC4VwtB6nZwKcY1KjGXqdvmnXkd0r95cNvzREfcyU/jxwCq2XjrMzZS7uOv0dK7alHFNetuFe8cmx/Pu1rmU8fbn8+7Pifqc4ePtC7iaeIvnWgygafmcbLApWem8vP47gr1L8Vn3Z6UvkeVO2j2mbJ5F3eAqdteMA9GnmXvYtSJwTzbqTgfJrJ6j42p/9Gl+PryOtpXqO5VWfsmJv9l66TBlvP2Z1vUZu/tWHoIgsPXSYf48tY1jsReJS0tEo9IQHhRGywp1mdisb4Fhsy6JC4Arkfs4fuR+OJ1JZeFAqWgSM9PoU+lJ6gW3e2gCo24FHbP7vkersp2wClaG/N4Wr7KeDi++y/66S4ZWB5L8E65iKyx2bPgBX193u+JkQaWr0K7T83ZZThUUFBQUFP6/Iy9ZCqBytdb5uS/MWDnid500rRG9t541V37j1O3d7B7/g503b3Hj466iYRXnn4BOnk8nw6IqdmHh5WWwExYGgyfNW49WhIWCgoKCwn8Sl8WFSqWiSfNheHoHcdwvliT9fUcPN18Da64s5NTtPSUuMGqU0zmV7hvg6vUsTl3OBHfnxYgccsLCYBBvU6VS0bz1k7g7yGynoKCgoKDw/x2XxQWARmfgSnkzdw32oX9uvgYOXpmP952t7C0hgVGznI7aYc4JBatV4MjJNCx63QOFn2rVmkKFBUCTFk9QpmzBzmAKCgoKCgr/nymSuPjj4o8cT8jJTCglEAvvBWXhcf0nfOI2cubFX+harZl02AMRm2Bm75lM0jMLT7t65FQaGYL6gZZDqgWU4/Azc6jj4c/Ov2bg4+MmKyzqNexLxcrNpWYFBQUFBYX/FC6Li9i0aE7fPSI1A+CLhdf1SfirrPj76PCOm4fl+FssGzyZH3u/ilsRvMTlSMkUuBJnYdfZLMwWx/6osbezOX81GzyK/r4Tm/bl8LNzuHfxIHs2z8TX1x2dzj4ipXrNDtSoVfyJexQUFBQUFP7XcDlaBMAqWDkRf4CtMau5mHQaAE+svKVLIlQtDlM1mqzEp7pjrP0BFu9whv75YX7sbHEwpf0oJjbtS5oxgQ+2TsyPFrmXbGbX4RSSrZoizVqU8fLntwFvU9O3NHu2zCErMxEfH/lIlFp1ulGrXg/ZPgUFBQUFhf8aRRIXtsSkXmFr9HLaJ6yiilo+pXGkUceGw6HUqtuBlu1H8WvEZqbu/JXE3GJOD4wgUCFAQ9s6BrQ6DacvpnP8YhaCh97lyqY6tYaJzfrxYaeniDy9k5NH1uPp6Yabm/zsR6Omg6lSvY3UrKCgoKCg8J/lgcVFHgm7m1FKRlzEmLVsOlsFX+8ArFYrJrOGek16U7l6c77Ys4jv9i/Pr3T3oLSv40ZYkIbFa+Mxe7qBpDJpQahy0/J+2e0ZspLucPyfZaSnxeHt7SmbZESt1tCs1Si7om4KCgoKCgr/dYpNXJw+NJw6xgsi2x2LhjXnKuPtEZhfc0MQBDIzs9HqfGjQYiDB5Wow5/BaZh1aww0nc9A74vGm7pyNzOBqnBnc7P0i5PDSuzO6UQ9eaTEQncXM8X/+JP72Zby85X0rALy8g2jZZgx+pf7dcvMKCgoKCgqPIsUmLq7G/EnF6C/y/06yqlhxvgIe+mD0BvubtNUqkJmRhd7Njxp1OlK9Zmt2XDnGryc2s/XS4fzc+q6g14LRKBQacqpWqWhdoR7D6nZkZINuxMScJfLUNuJvX8bTy102EiSP8hUa0bj5UHQ6N2mXgoKCgoKCQnGKC6vVTMq+5viqBNIFFdvOXMfdoibLvwtGVSnp8HwEQSAry4jJJFCpanPKVW1CaNkq7I2KYPm5PeyPOc3F+Binqs4VRDmfIJqVr0W/8NY8XrM1qan3uHHlGJFn92A2p+PubkCvtxdBeej07tRv1I+KlZsrjpsKCgoKCgoFUGziAuD0P/2pZolma2QcpT0qUa3Fq/hX7MO1qKOcjliHMbcqoyNMJhPZWSYEtJSrUI+yFepRpmxVPNy9OH3zEgdvnCc6OY6bqXe5mXKX26mJZJmzMVstaFQadBoNpb38CfEOIsQnkBDvQJqGVKdxaA10Gi03b13hTswZoq8cJys7GYNBj8GgR1OIb0bFys2p17APBjdxlVUFBQUFBQUFe4pVXFy88CNxV9ZTp8EHlAptKerLzkrj9In1XIs6hDNvaTZbyM42YjabUavdCAiqQGBgedy8SqH39MPDyw8vTz90Gh1qtRpBEDBbzKRnpJCenkRWehLG9HvcS4glPu4aWZlJaHVadDotBkPOawrDz78cDZsOIjCokrRLQUFBQUFBwQHFKi6cIS31LhfPbefqlYMIQuEZNvOwWq2YTRYsVitWizXn/1YrCCDkLpqoUKFSq1CrVWg0atRqNRqNBq1W49JSRkBgRWrW6UpwSC2XXqegoKCgoKDwL4iLPDIykog8t4NrVw9jMmZKu/8VypQNJ7xWZ4LKVFVEhYKCgoKCQhH518RFHhaLmVuxZ4mOOsytm+dcms0oDnz9QqhQqSlhFRvh7lH8RdYUFBQUFBT+a/zr4sKW7Kw0bt86z53bkcTdjiQzI0k65IHRavUElq5C6TLVCC5bE1//EOkQBQUFBQUFhQfgkRIXtgiCQHraXe7GR5GSHEdqShypyXdIS4t3yiEUwN3DD2/v0nj7BOHlU5qAwIr4lyqPWu16rREFBQUFBQUF53hkxYUjrFYLJmMmJlMWJlMWZlMWZnM2arUGtVqLTueGTu+Bwc0LbTFVYVVQUFBQUFBwnv85caGgoKCgoKDwaFN4sgcFBQUFBQUFBRf4P9kffOTzFfyWAAAAAElFTkSuQmCC"

// ⭐ LOGO DO SIGEP DA DEFENSORIA (Proporção real 535x120px)
const LOGO_DEFENSORIA_RATIO = 535 / 120;

// ⭐ FUNÇÃO: Desativada para não aparecer nos outros relatórios
const addLogoHeader = (doc, startY = 20) => {
    return false; // Retorna falso para não renderizar nos demais PDFs
};

// ⭐ FUNÇÃO: Adiciona rodapé padrão
const addFooter = (doc, pageNumber, totalPages) => {
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`SIGEP - Sistema de Gerenciamento de Pauta | ${new Date().toLocaleString('pt-BR')} | Página ${pageNumber}`, 
             doc.internal.pageSize.getWidth() / 2, pageHeight - 10, { align: 'center' });
};

// ⭐ FUNÇÃO GARANTIDA: buildAtaAcaoSocialPDF - APENAS LOGO CENTRAL
const buildAtaAcaoSocialPDF = async (doc, pautaName, colaboradores, atendidos, dadosExtras = {}) => {
    console.log("📄 Iniciando geração da Ata Social...");
    
    const dataInput = dadosExtras.data ? new Date(dadosExtras.data + 'T12:00:00') : new Date();
    const dia = dataInput.getDate();
    const mesExtenso = dataInput.toLocaleString('pt-BR', { month: 'long' });
    const ano = dataInput.getFullYear();
    
    const endereco = dadosExtras.endereco || "Não informado";
    const nomeDaAcao = dadosExtras.acao || pautaName;
    const orgaoAtendimentoConteudo = dadosExtras.orgao || "NÃO INFORMADO";
    const totalAtendidos = dadosExtras.totalAtendimentos !== undefined 
        ? dadosExtras.totalAtendimentos 
        : atendidos.length;

    // ⭐⭐⭐ LOGO RENDERIZADA CENTRALIZADA (ÚNICA NA ATA) ⭐⭐⭐
    try {
        if (LOGO_PADRAO_BASE64 && LOGO_PADRAO_BASE64.startsWith("data:image")) {
            const pageWidth = doc.internal.pageSize.getWidth();
            
            const logoWidth = 90; // Mantido o tamanho maior original da Defensoria
            const logoHeight = logoWidth / LOGO_DEFENSORIA_RATIO; 
            const xPos = (pageWidth - logoWidth) / 2;
            
            doc.addImage(LOGO_PADRAO_BASE64, 'PNG', xPos, 8, logoWidth, logoHeight);
            console.log("✅ Logo inserida com sucesso no PDF da Ata!");
        }
    } catch(e) { 
        console.error("❌ Erro ao inserir logo no PDF:", e); 
    }

    // Título
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text("ATA AÇÃO SOCIAL", 105, 52, { align: "center" });

    // Texto introdutório
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    
    const introText = `Aos ${dia} dias do mês de ${mesExtenso} do ano de ${ano}, a partir das 9h, em ${endereco}, trabalharam na ${nomeDaAcao}, os(as) Defensores(as) Públicos(as) abaixo listados(as), bem como os(as) servidores(as), conforme listagem a seguir:`;
    
    const splitIntro = doc.splitTextToSize(introText, 170);
    doc.text(splitIntro, 20, 62);
    
    let currentY = 62 + (splitIntro.length * 4.5);

    // Ordena colaboradores
    const sortedColaboradores = [...colaboradores].sort((a, b) => {
        const eqA = a.equipe || '';
        const eqB = b.equipe || '';
        if (eqA !== eqB) return eqA.localeCompare(eqB);
        return (a.nome || '').localeCompare(b.nome || '');
    });

    const defensores = sortedColaboradores.filter(c => c.cargo && c.cargo.toLowerCase().includes('defensor'));
    const servidores = sortedColaboradores.filter(c => c.cargo && !c.cargo.toLowerCase().includes('defensor'));

    const larguraNome = 65;
    const larguraIdentificador = 30;
    const larguraAssinatura = 170 - larguraNome - larguraIdentificador;

    // Tabela de Defensores
    if (defensores.length > 0) {
        doc.autoTable({
            startY: currentY + 1,
            head: [[{ content: 'DEFENSOR(A) PÚBLICO(A)', colSpan: 3, styles: { halign: 'center', fontStyle: 'bold', fontSize: 9, fillColor: [146, 208, 80] } }]],
            body: [
                [
                    { content: 'NOME', styles: { fillColor: [226, 239, 218], fontStyle: 'bold', halign: 'center', fontSize: 8 } },
                    { content: 'MATRÍCULA', styles: { fillColor: [226, 239, 218], fontStyle: 'bold', halign: 'center', fontSize: 8 } },
                    { content: 'ASSINATURA', styles: { fillColor: [226, 239, 218], fontStyle: 'bold', halign: 'center', fontSize: 8 } }
                ],
                ...defensores.map(c => [
                    { content: c.nome || '', styles: { halign: 'center', fontSize: 8, cellPadding: 2 } },
                    { content: getIdentificador(c), styles: { halign: 'center', fontSize: 8, cellPadding: 2 } },
                    { content: '', styles: { halign: 'center', fontSize: 8, cellPadding: 2 } }
                ])
            ],
            theme: 'grid',
            headStyles: { fillColor: [146, 208, 80], textColor: [0, 0, 0], halign: 'center', fontStyle: 'bold', fontSize: 9 },
            styles: { fontSize: 8, cellPadding: 2.5, lineColor: [0, 0, 0], lineWidth: 0.2, valign: 'middle', halign: 'center' },
            columnStyles: { 0: { cellWidth: larguraNome }, 1: { cellWidth: larguraIdentificador }, 2: { cellWidth: larguraAssinatura } },
            margin: { left: 20, right: 20 }
        });
        currentY = doc.lastAutoTable.finalY + 2;
    }

    // Tabela de Servidores
    if (servidores.length > 0) {
        doc.autoTable({
            startY: currentY,
            head: [[{ content: 'SERVIDOR(A)', colSpan: 3, styles: { halign: 'center', fontStyle: 'bold', fontSize: 9, fillColor: [146, 208, 80] } }]],
            body: [
                [
                    { content: 'NOME', styles: { fillColor: [226, 239, 218], fontStyle: 'bold', halign: 'center', fontSize: 8 } },
                    { content: 'ID FUNCIONAL', styles: { fillColor: [226, 239, 218], fontStyle: 'bold', halign: 'center', fontSize: 8 } },
                    { content: 'ASSINATURA', styles: { fillColor: [226, 239, 218], fontStyle: 'bold', halign: 'center', fontSize: 8 } }
                ],
                ...servidores.map(c => [
                    { content: c.nome || '', styles: { halign: 'center', fontSize: 8, cellPadding: 2 } },
                    { content: getIdentificador(c), styles: { halign: 'center', fontSize: 8, cellPadding: 2 } },
                    { content: '', styles: { halign: 'center', fontSize: 8, cellPadding: 2 } }
                ])
            ],
            theme: 'grid',
            headStyles: { fillColor: [146, 208, 80], textColor: [0, 0, 0], halign: 'center', fontStyle: 'bold', fontSize: 9 },
            styles: { fontSize: 8, cellPadding: 2.5, lineColor: [0, 0, 0], lineWidth: 0.2, valign: 'middle', halign: 'center' },
            columnStyles: { 0: { cellWidth: larguraNome }, 1: { cellWidth: larguraIdentificador }, 2: { cellWidth: larguraAssinatura } },
            margin: { left: 20, right: 20 }
        });
        currentY = doc.lastAutoTable.finalY + 2;
    }

    // Órgão e Total
    doc.autoTable({
        startY: currentY,
        body: [
            [
                { content: 'ÓRGÃO DE ATENDIMENTO - AS', styles: { fillColor: [226, 239, 218], fontStyle: 'bold', halign: 'center', fontSize: 8 } },
                { content: 'TOTAL DE ATENDIMENTOS', styles: { fillColor: [226, 239, 218], fontStyle: 'bold', halign: 'center', fontSize: 8 } }
            ],
            [
                { content: orgaoAtendimentoConteudo.toUpperCase(), styles: { halign: 'center', fontSize: 8, cellPadding: 3 } },
                { content: String(totalAtendidos), styles: { halign: 'center', fontSize: 10, fontStyle: 'bold', cellPadding: 3 } }
            ]
        ],
        theme: 'grid',
        styles: { fontSize: 8, halign: 'center', cellPadding: 3, lineColor: [0, 0, 0], lineWidth: 0.2, valign: 'middle' },
        columnStyles: { 0: { cellWidth: 110 }, 1: { cellWidth: 60 } },
        margin: { left: 20, right: 20 }
    });
    
    currentY = doc.lastAutoTable.finalY + 6;

    // Observações
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.text("OBSERVAÇÕES:", 20, currentY);
    doc.setDrawColor(0, 0, 0);
    doc.line(20, currentY + 3, 190, currentY + 3);
    
    for (let i = 1; i <= 3; i++) {
        const lineY = currentY + 6 + (i * 4.5);
        if (lineY < doc.internal.pageSize.getHeight() - 15) {
            doc.setDrawColor(200, 200, 200);
            doc.line(20, lineY, 190, lineY);
        }
    }
    
    console.log("✅ Ata Social gerada com sucesso!");
};

const generateCollaboratorsTable = (docPDF, colaboradores, pautaNome, campos) => {
    const colMap = {
        'nome': { label: 'Membro', getData: (c) => c.nome || 'N/A' },
        'cargo': { label: 'Cargo', getData: (c) => c.cargo || 'N/A' },
        'equipe': { label: 'Equipe', getData: (c) => c.equipe ? `EQP ${c.equipe}` : 'N/A' },
        'transporte': { label: 'Deslocamento', getData: (c) => {
            let desc = c.transporte || 'Não Informado';
            if (c.transporte === 'Com a Empresa' && c.localEncontro) desc += ` (${c.localEncontro})`;
            return desc;
        }},
        'status': { label: 'Status', getData: (c) => c.presente ? 'Presente' : 'Ausente' },
        'presenca': { label: 'Status / Horário', getData: (c) => c.presente ? `Presente (${c.horario})` : 'Ausente' },
        'identificador': { label: 'Matrícula/ID', getData: (c) => getIdentificador(c) }
    };

    const header = [campos.map(key => colMap[key]?.label || key)];
    
    const sortedColaboradores = [...colaboradores].sort((a, b) => {
        const equipeA = a.equipe || 'Sem Equipe';
        const equipeB = b.equipe || 'Sem Equipe';
        if (equipeA !== equipeB) return equipeA.localeCompare(equipeB);

        const getCargoWeight = (cargo) => {
            const c = (cargo || '').toLowerCase();
            if (c.includes('defensor')) return 1;
            if (c.includes('servidor')) return 2;
            return 3;
        };

        const weightA = getCargoWeight(a.cargo);
        const weightB = getCargoWeight(b.cargo);
        
        if (weightA !== weightB) return weightA - weightB;
        return (a.nome || '').localeCompare(b.nome || '');
    });

    const tableData = [];
    let currentEquipe = null;

    sortedColaboradores.forEach(c => {
        const equipeAtual = c.equipe ? `Equipe ${c.equipe}` : 'Sem Equipe';
        
        if (equipeAtual !== currentEquipe) {
            currentEquipe = equipeAtual;
            tableData.push([
                {
                    content: equipeAtual.toUpperCase(),
                    colSpan: campos.length,
                    styles: { fillColor: [240, 253, 244], textColor: [21, 128, 61], fontStyle: 'bold', halign: 'center' }
                }
            ]);
        }
        
        tableData.push(campos.map(key => colMap[key] ? colMap[key].getData(c) : 'N/A'));
    });

    docPDF.autoTable({
        head: header,
        body: tableData,
        startY: 70,
        theme: 'striped',
        headStyles: { fillColor: [22, 163, 74] },
        styles: { fontSize: 9, halign: 'center', valign: 'middle' }
    });
};

// ========================================================
// PDF SERVICE - EXPORT
// ========================================================

export const PDFService = {
    
    async generatePlanilhaGastosPDF(assistedName, expenseData) {
        try {
            await ensureJsPDF(); 
            const { jsPDF } = window.jspdf;
            const doc = new jsPDF({ orientation: 'p', unit: 'pt', format: 'a4' });

            doc.setFont("helvetica", "bold");
            doc.setFontSize(14);
            doc.text("PLANILHA DE DESPESAS ATUAIS", doc.internal.pageSize.getWidth() / 2, 60, { align: "center" });

            doc.setFont("helvetica", "normal");
            doc.setFontSize(10);
            doc.text(`Assistido(a): ${assistedName}`, 40, 90);

            doc.autoTable({
                startY: 110,
                head: [["Categoria", "Valor Mensal (R$)"]],
                body: [
                    ["Moradia", formatCurrency(expenseData?.moradia)],
                    ["Alimentação", formatCurrency(expenseData?.alimentacao)],
                    ["Educação", formatCurrency(expenseData?.educacao)],
                    ["Saúde", formatCurrency(expenseData?.saude)],
                    ["Vestuário e Higiene", formatCurrency(expenseData?.vestuario)],
                    ["Lazer e Transporte", formatCurrency(expenseData?.lazer)],
                    ["Outras Despesas", formatCurrency(expenseData?.outras)]
                ],
                margin: { left: (doc.internal.pageSize.getWidth() - 430) / 2 },
                theme: 'striped',
                headStyles: { fillColor: [22, 163, 74] }
            });

            doc.save(`Planilha_Despesas_${(assistedName||'Assistido').replace(/\s+/g, '_')}.pdf`);
            return true;
        } catch (error) {
            console.error("Erro PDF Planilha:", error);
            return false;
        }
    },

    async generateAtaAcaoSocial(pautaName, colaboradores, atendidos, dadosExtras = {}) {
        try {
            await ensureJsPDF();
            const { jsPDF } = window.jspdf;
            const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });
            
            await buildAtaAcaoSocialPDF(doc, pautaName, colaboradores, atendidos, dadosExtras);
            
            doc.save(`Ata_Social_${(dadosExtras.acao || pautaName).replace(/\s+/g, '_')}.pdf`);
            return true;
            
        } catch (error) {
            console.error("Erro ao gerar Ata Social:", error);
            return false;
        }
    },

    async previewAtaAcaoSocial(pautaName, colaboradores, atendidos, dadosExtras = {}) {
        try {
            await ensureJsPDF();
            const { jsPDF } = window.jspdf;
            const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });
            
            await buildAtaAcaoSocialPDF(doc, pautaName, colaboradores, atendidos, dadosExtras);
            
            const pdfBlob = doc.output('blob');
            const pdfUrl = URL.createObjectURL(pdfBlob);
            window.open(pdfUrl, '_blank');
            return true;
            
        } catch (error) {
            console.error("Erro ao gerar Preview da Ata Social:", error);
            return false;
        }
    },

    async generateAtendidosPDF(arg1, arg2) {
        try {
            await ensureJsPDF();
            const { jsPDF } = window.jspdf;
            const docPDF = new jsPDF({ orientation: 'l', unit: 'pt', format: 'a4' });

            addLogoHeader(docPDF, 20);

            const atendidosList = Array.isArray(arg1) ? arg1 : (Array.isArray(arg2) ? arg2 : []);
            const pautaNome = typeof arg1 === 'string' ? arg1 : (typeof arg2 === 'string' ? arg2 : 'Geral');

            docPDF.setFontSize(18);
            docPDF.setTextColor(22, 163, 74); 
            docPDF.text(`Relatório de Atendidos - ${pautaNome}`, 40, 55);

            docPDF.setFontSize(10);
            docPDF.setTextColor(100);
            const totalAssuntos = atendidosList.reduce((acc, a) => acc + 1 + (a.demandas?.quantidade || 0), 0);
            docPDF.text(`Data: ${new Date().toLocaleString('pt-BR')}`, 40, 70);
            docPDF.text(`Total: ${atendidosList.length} assistidos | Assuntos totais: ${totalAssuntos}`, 40, 83);

            const head = [["#", "Nome", "Agendado", "Chegou", "Chamado", "Duração", "Assunto", "Atendente", "Validado Verde"]];

            const body = atendidosList.map((item, index) => {
                const arrivalDate = getSafeDate(item.arrivalTime);
                const attendedDate = getSafeDate(item.attendedTime);

                let duration = 'N/A';
                if (arrivalDate && attendedDate) {
                    const diffMs = attendedDate.getTime() - arrivalDate.getTime();
                    duration = calculateDuration(Math.round(diffMs / 60000));
                }

                const arrStr = arrivalDate ? arrivalDate.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }) : '---';
                const attStr = attendedDate ? attendedDate.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }) : '---';
                let atendente = getAttendantNameForPDF(item);

                return [
                    index + 1,
                    cleanString(item.name),
                    item.scheduledTime || (item.type === 'avulso' ? 'Avulso' : '---'),
                    arrStr,
                    attStr,
                    duration,
                    cleanString(item.subject),
                    cleanString(atendente),
                    item.isConfirmed ? "CONCLUÍDO" : "PENDENTE"
                ];
            });

            if (body.length === 0) body.push([{ content: "Nenhum atendimento finalizado nesta pauta.", colSpan: 9, styles: { halign: 'center', fontStyle: 'italic' } }]);

            docPDF.autoTable({
                head: head,
                body: body,
                startY: 100,
                theme: 'striped',
                headStyles: { fillColor: [22, 163, 74] },
                styles: { fontSize: 8, cellPadding: 4, halign: 'center' },
                columnStyles: { 0: { cellWidth: 25 }, 1: { cellWidth: 110 }, 6: { cellWidth: 150 } }
            });

            addFooter(docPDF, 1, 1);

            docPDF.save(`atendidos_${pautaNome.replace(/\s+/g, '_')}.pdf`);
            return true;
        } catch (error) {
            console.error("Erro PDF Atendidos:", error);
            return false;
        }
    },
    
    async generateFaltososPDF(arg1, arg2) {
        try {
            await ensureJsPDF();
            const { jsPDF } = window.jspdf;
            const docPDF = new jsPDF({ orientation: 'p', unit: 'pt', format: 'a4' });

            addLogoHeader(docPDF, 20);

            const faltososList = Array.isArray(arg1) ? arg1 : (Array.isArray(arg2) ? arg2 : []);
            const pautaNome = typeof arg1 === 'string' ? arg1 : (typeof arg2 === 'string' ? arg2 : 'Geral');

            docPDF.setFontSize(18);
            docPDF.setTextColor(22, 163, 74);
            docPDF.text(`Relatório de Faltosos - ${pautaNome}`, 40, 55);

            docPDF.setFontSize(10);
            docPDF.setTextColor(100);
            docPDF.text(`Data de Emissão: ${new Date().toLocaleString('pt-BR')}`, 40, 70);
            docPDF.text(`Total de Ausências: ${faltososList.length}`, 40, 83);

            const head = [["#", "Nome do Assistido", "Agendado", "Assunto", "Falta às", "Verde"]];

            const body = faltososList.map((item, index) => {
                const logTime = getSafeDate(item.lastActionTimestamp);
                const faltaStr = logTime ? logTime.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }) : '---';

                return [
                    index + 1,
                    cleanString(item.name).toUpperCase(),
                    item.scheduledTime || (item.type === 'avulso' ? 'Avulso' : '---'),
                    cleanString(item.subject).toUpperCase(), 
                    faltaStr,
                    item.isConfirmed ? "OK" : "PEND"
                ];
            });

            if (body.length === 0) body.push([{ content: "Nenhum assistido marcado como faltoso.", colSpan: 6, styles: { halign: 'center', fontStyle: 'italic' } }]);

            docPDF.autoTable({
                head: head,
                body: body,
                startY: 100,
                theme: 'grid',
                headStyles: { fillColor: [22, 163, 74] },
                styles: { fontSize: 8, cellPadding: 5, halign: 'center', valign: 'middle', overflow: 'linebreak' },
                columnStyles: { 
                    1: { halign: 'left', cellWidth: 140 }, 
                    3: { halign: 'left', cellWidth: 160 }, 
                    5: { fontStyle: 'bold' } 
                }
            });

            addFooter(docPDF, 1, 1);

            docPDF.save(`faltosos_${pautaNome.replace(/\s+/g, '_')}.pdf`);
            return true;
        } catch (error) {
            console.error("Erro PDF Faltosos:", error);
            return false;
        }
    },

    async generateCollaboratorsPDF(arg1, arg2, arg3) {
        try {
            await ensureJsPDF();
            const { jsPDF } = window.jspdf;
            const docPDF = new jsPDF();

            addLogoHeader(docPDF, 15);

            let colaboradores = [];
            let pautaNome = 'Geral';
            let colunas = ['nome', 'cargo', 'equipe', 'transporte'];

            if (arg1 && !Array.isArray(arg1) && arg1.colaboradores) {
                colaboradores = arg1.colaboradores || [];
                pautaNome = arg1.pautaNome || 'Geral';
                colunas = arg1.colunas || ['nome', 'cargo', 'equipe', 'transporte'];
            } else if (Array.isArray(arg1)) {
                colaboradores = arg1;
                if (typeof arg2 === 'string') pautaNome = arg2;
                if (Array.isArray(arg3)) colunas = arg3;
            }

            if (!colaboradores || colaboradores.length === 0) {
                console.warn("Nenhum colaborador na lista para gerar PDF.");
                return false;
            }

            const colMap = {
                'nome': { label: 'Membro da Equipe', getData: (c) => c.nome },
                'cargo': { label: 'Cargo', getData: (c) => c.cargo || 'N/A' },
                'equipe': { label: 'Equipe', getData: (c) => c.equipe ? `EQP ${c.equipe}` : 'N/A' },
                'presenca': { label: 'Status / Horário', getData: (c) => c.presente ? `Presente (${c.horario})` : 'Ausente' },
                'identificador': { label: 'Matrícula/ID', getData: (c) => c.identificador || 'N/A' },
                'telefone': { label: 'Telefone', getData: (c) => c.telefone || 'N/A' },
                'email': { label: 'E-mail', getData: (c) => c.email || 'N/A' },
                'horario': { label: 'Chegada', getData: (c) => c.horario || '--:--' },
                'transporte': { label: 'Deslocamento', getData: (c) => {
                    let desc = c.transporte || 'Não Informado';
                    if (c.transporte === 'Com a Empresa' && c.localEncontro) desc += ` (${c.localEncontro})`;
                    return desc;
                }}
            };

            const sortedColaboradores = [...colaboradores].sort((a, b) => {
                const equipeA = a.equipe || 'Sem Equipe';
                const equipeB = b.equipe || 'Sem Equipe';
                if (equipeA !== equipeB) return equipeA.localeCompare(equipeB);

                const getCargoWeight = (cargo) => {
                    const c = (cargo || '').toLowerCase();
                    if (c.includes('defensor')) return 1;
                    if (c.includes('servidor')) return 2;
                    return 3;
                };

                const weightA = getCargoWeight(a.cargo);
                const weightB = getCargoWeight(b.cargo);
                
                if (weightA !== weightB) return weightA - weightB;
                return (a.nome || '').localeCompare(b.nome || '');
            });

            const header = [colunas.map(key => colMap[key] ? colMap[key].label : key)];
            const tableData = [];
            let currentEquipe = null;

            sortedColaboradores.forEach(c => {
                const equipeAtual = c.equipe ? `Equipe ${c.equipe}` : 'Sem Equipe';
                
                if (equipeAtual !== currentEquipe) {
                    currentEquipe = equipeAtual;
                    tableData.push([
                        {
                            content: equipeAtual.toUpperCase(),
                            colSpan: colunas.length, 
                            styles: { fillColor: [240, 253, 244], textColor: [21, 128, 61], fontStyle: 'bold', halign: 'center' }
                        }
                    ]);
                }
                
                tableData.push(colunas.map(key => colMap[key] ? colMap[key].getData(c) : 'N/A'));
            });

            docPDF.setFontSize(16);
            docPDF.setTextColor(22, 163, 74); 
            docPDF.text("Lista de Presença da Equipe", 14, 40);
            
            docPDF.setFontSize(10);
            docPDF.text(`Pauta: ${pautaNome}`, 14, 55);

            docPDF.autoTable({
                head: header,
                body: tableData,
                startY: 70,
                theme: 'striped',
                headStyles: { fillColor: [22, 163, 74] },
                styles: { fontSize: 9, halign: 'center', valign: 'middle' }
            });

            addFooter(docPDF, 1, 1);

            docPDF.save(`equipe_${pautaNome.replace(/\s+/g, '_')}.pdf`);
            return true;
        } catch (e) {
            console.error("Erro PDF Equipe:", e);
            return false;
        }
    },
    
    async generateChecklistPDF(assistedName, actionTitle, checklistData, documentosTextos) {
        try {
            await ensureJsPDF();
            const { jsPDF } = window.jspdf;
            const doc = new jsPDF({ orientation: 'p', unit: 'pt', format: 'a4' });

            let y = 60; 
            const marginX = 50; 
            const maxWidth = doc.internal.pageSize.getWidth() - (marginX * 2);
            const pageHeight = doc.internal.pageSize.getHeight();

            addLogoHeader(doc, 15);

            const checkPage = (heightToAdd = 20) => {
                if (y + heightToAdd >= pageHeight - 50) {
                    const pageNumber = doc.internal.getNumberOfPages() + 1;
                    addFooter(doc, pageNumber, 1);
                    doc.addPage();
                    y = 60;
                    addLogoHeader(doc, 15);
                }
            };

            const addText = (text, isBold = false, size = 10, indent = 0) => {
                doc.setFont("helvetica", isBold ? "bold" : "normal");
                doc.setFontSize(size);
                const textLines = doc.splitTextToSize(text, maxWidth - indent);
                checkPage(textLines.length * (size * 1.2));
                doc.text(textLines, marginX + indent, y);
                y += (textLines.length * (size * 1.2)) + 5;
            };

            doc.setFont("helvetica", "bold");
            doc.setFontSize(14);
            doc.text("Checklist de Atendimento - SIGEP", doc.internal.pageSize.getWidth() / 2, y, { align: "center" });
            y += 40;

            addText(`Assistido: ${assistedName.toUpperCase()}`, false, 11);
            addText(`Ação: ${actionTitle}`, false, 11);
            y += 30;

            addText("DOCUMENTAÇÃO ENTREGUE:", true, 11);
            y += 10;
            
            documentosTextos.forEach((item) => {
                if (item.id.startsWith('reu-') || item.id.startsWith('gastos-') || item.id.startsWith('gasto-')) return;
                const tipoEntrega = checklistData.docTypes && checklistData.docTypes[item.id] ? checklistData.docTypes[item.id] : 'Físico';
                addText(`[X] ${item.text} - [${tipoEntrega.toUpperCase()}]`, false, 10, 20); 
            });
            y += 20;

            if (checklistData.demandasAdicionais && checklistData.demandasAdicionais.length > 0) {
                addText("DEMANDAS ADICIONAIS:", true, 11);
                y += 10;
                checklistData.demandasAdicionais.forEach((demanda) => {
                    addText(`• ${demanda}`, false, 10, 20);
                });
                y += 20;
            }

            if (checklistData.expenseData && checklistData.expenseData.checkExibirGastos) {
                const g = checklistData.expenseData;
                addText("PLANILHA DE GASTOS:", true, 11);
                y += 10;
                
                const categoriasNome = [
                    { id: 'moradia', label: '1. MORADIA (Habitação)' },
                    { id: 'alimentacao', label: '2. ALIMENTAÇÃO' },
                    { id: 'educacao', label: '3. EDUCAÇÃO' },
                    { id: 'saude', label: '4. SAÚDE' },
                    { id: 'vestuario', label: '5. VESTUÁRIO E HIGIENE' },
                    { id: 'lazer', label: '6. LAZER E TRANSPORTE' },
                    { id: 'outras', label: '7. OUTRAS DESPESAS' }
                ];

                let totalGastos = 0;
                categoriasNome.forEach(c => {
                    const valorStr = g[c.id] || 'R$ 0,00';
                    if (valorStr !== 'R$ 0,00') {
                        addText(`${c.label}: ${valorStr}`, false, 10, 20); 
                        const num = parseFloat(String(valorStr).replace(/[R$\s]/g, '').replace(/\./g, '').replace(',', '.')) || 0;
                        totalGastos += num;
                    }
                });

                if (totalGastos > 0) {
                    y += 5; 
                    const totalFormatado = totalGastos.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
                    addText(`TOTAL: ${totalFormatado}`, true, 10, 20); 
                }
                y += 20;
            }

            if (checklistData.reuData && checklistData.reuData.checkReuUnico) {
                const r = checklistData.reuData;
                addText("DADOS DA PARTE CONTRÁRIA (RÉU):", true, 11);
                y += 10;
                
                if (r.nome) addText(`Nome: ${r.nome.toUpperCase()}`, false, 10, 20);
                
                let contatoStr = '';
                if (r.cpf) contatoStr += `CPF: ${r.cpf}`;
                if (r.telefone) {
                    if (contatoStr) contatoStr += ` | `;
                    contatoStr += `WhatsApp: ${r.telefone}`;
                }
                if (contatoStr) addText(contatoStr, false, 10, 20);
                
                if (r.rua) {
                    let endStr = `Endereço: ${r.rua}`;
                    if(r.numero) endStr += `, ${r.numero}`;
                    if(r.complemento) endStr += ` - ${r.complemento}`;
                    if(r.bairro) endStr += ` - ${r.bairro}`;
                    addText(endStr, false, 10, 20);
                    
                    let cidStr = '';
                    if(r.cidade) cidStr += `Cidade: ${r.cidade}`;
                    if(r.uf) cidStr += `/${r.uf}`;
                    if(r.cep) {
                        if (cidStr) cidStr += ` | `;
                        cidStr += `CEP: ${r.cep}`;
                    }
                    if (cidStr) addText(cidStr, false, 10, 20);
                }

                if (r.empresa) {
                    y += 5;
                    addText(`Empresa (Trabalho): ${r.empresa.toUpperCase()}`, false, 10, 20);
                    
                    let endComStr = `End. Comercial: ${r.rua_comercial}`;
                    if(r.numero_comercial) endComStr += `, ${r.numero_comercial}`;
                    if(r.complemento_comercial) endComStr += ` - ${r.complemento_comercial}`;
                    if(r.bairro_comercial) endComStr += ` - ${r.bairro_comercial}`;
                    addText(endComStr, false, 10, 20);

                    let cidComStr = '';
                    if(r.cidade_comercial) cidComStr += `Cidade: ${r.cidade_comercial}`;
                    if(r.uf_comercial) cidComStr += `/${r.uf_comercial}`;
                    if(r.cep_comercial) {
                        if (cidComStr) cidComStr += ` | `;
                        cidComStr += `CEP: ${r.cep_comercial}`;
                    }
                    if (cidComStr) addText(cidComStr, false, 10, 20);
                }

                let temDadosReuSocio = false;
                const dadosReuSocio = [];
                
                let ocupacao = r.ocupacao;
                if (r.ocupacaoNaoSei) ocupacao = 'Não informado (Não soube informar)';
                if (ocupacao && ocupacao.trim() !== '' && !r.ocupacaoNaoSei) {
                    dadosReuSocio.push(`Ocupação: ${ocupacao}`);
                    temDadosReuSocio = true;
                } else if (r.ocupacaoNaoSei) {
                    dadosReuSocio.push(`Ocupação: Não informado (Não soube informar)`);
                    temDadosReuSocio = true;
                }
                
                let profissao = r.profissao;
                if (r.profissaoNaoSei) profissao = 'Não informado (Não soube informar)';
                if (profissao && profissao.trim() !== '' && !r.profissaoNaoSei) {
                    dadosReuSocio.push(`Profissão: ${profissao}`);
                    temDadosReuSocio = true;
                } else if (r.profissaoNaoSei) {
                    dadosReuSocio.push(`Profissão: Não informado (Não soube informar)`);
                    temDadosReuSocio = true;
                }
                
                let estadoCivil = r.estadoCivil;
                if (r.estadoCivilNaoSei) estadoCivil = 'Não informado (Não soube informar)';
                if (estadoCivil && estadoCivil.trim() !== '' && !r.estadoCivilNaoSei) {
                    dadosReuSocio.push(`Estado Civil: ${estadoCivil}`);
                    temDadosReuSocio = true;
                } else if (r.estadoCivilNaoSei) {
                    dadosReuSocio.push(`Estado Civil: Não informado (Não soube informar)`);
                    temDadosReuSocio = true;
                }
                
                let ganhos = r.ganhos;
                if (r.ganhosNaoSei) ganhos = 'Não informado (Não soube informar)';
                if (ganhos && ganhos.trim() !== '' && ganhos !== 'R$ 0,00' && !r.ganhosNaoSei) {
                    dadosReuSocio.push(`Ganhos Líquidos: ${ganhos}`);
                    temDadosReuSocio = true;
                } else if (r.ganhosNaoSei) {
                    dadosReuSocio.push(`Ganhos Líquidos: Não informado (Não soube informar)`);
                    temDadosReuSocio = true;
                }
                
                if (r.fonteRenda && r.fonteRenda.trim() !== '') {
                    dadosReuSocio.push(`Fonte de Renda: ${r.fonteRenda}`);
                    temDadosReuSocio = true;
                }
                
                if (temDadosReuSocio) {
                    y += 10;
                    addText("PERFIL SOCIOECONÔMICO DO RÉU:", true, 11);
                    y += 10;
                    dadosReuSocio.forEach(dado => {
                        addText(`• ${dado}`, false, 10, 20);
                    });
                    y += 20;
                }
            }

            const totalPages = doc.internal.getNumberOfPages();
            for (let i = 1; i <= totalPages; i++) {
                doc.setPage(i);
                addFooter(doc, i, totalPages);
            }

            doc.save(`Checklist_SIGEP_${assistedName.replace(/\s+/g, '_')}.pdf`);
            return true;
        } catch (err) {
            console.error("Erro crítico na montagem do PDF textual:", err);
            return false;
        }
    }
};

// ⭐ EXPORTS AVULSOS
export const generateAtendidosPDF = (arg1, arg2) => PDFService.generateAtendidosPDF(arg1, arg2);
export const generateChecklistPDF = (assistedName, actionTitle, checklistData, documentosTextos) => PDFService.generateChecklistPDF(assistedName, actionTitle, checklistData, documentosTextos);
export const generateCollaboratorsPDF = (arg1, arg2, arg3) => PDFService.generateCollaboratorsPDF(arg1, arg2, arg3);
export const generateFaltososPDF = (arg1, arg2) => PDFService.generateFaltososPDF(arg1, arg2);

window.PDFService = PDFService;
